'use strict';

const SAVE_KEY = 'craque-sss-save-v3';
const VERSION = 3;
const WEEK_LIMIT = 3;
const POSITIONS = ['Atacante', 'Ponta', 'Meia', 'Volante', 'Zagueiro', 'Goleiro'];
const ATTR_META = { ritmo:{label:'Ritmo',group:'Físico'},fisico:{label:'Físico',group:'Físico'},finalizacao:{label:'Finalização',group:'Técnico'},passe:{label:'Passe',group:'Técnico'},drible:{label:'Drible',group:'Técnico'},visao:{label:'Visão',group:'Mental'},mental:{label:'Mental',group:'Mental'},defesa:{label:'Defesa',group:'Defesa'},reflexo:{label:'Reflexo',group:'Goleiro'} };
const PHYSICAL = new Set(['ritmo','fisico','reflexo']);
const CATEGORY_RULES = [
  {name:'Sub-15',minOvr:0,minAge:15,club:'Academia Local'},
  {name:'Sub-17',minOvr:40,minAge:16,club:'Academia Local'},
  {name:'Estreante Profissional',minOvr:55,minAge:17,club:'Clube Profissional'},
  {name:'Europa',minOvr:72,minAge:18,club:'Clube Europeu'},
  {name:'Seleção Principal',minOvr:84,minAge:19,club:'Seleção Principal'}
];
const TRAINING = {leve:{label:'Leve',cost:18,chance:1,gain:[1,2],injury:0,fatigue:0,focus:'mental'},pesado:{label:'Pesado',cost:30,chance:.72,gain:[2,4],injury:.08,fatigue:14,focus:'físico'},espartano:{label:'Espartano',cost:48,chance:.42,gain:[4,7],injury:.18,fatigue:28,focus:'físico'}};
const APPROACHES = {seguro:{label:'Seguro',scoreMod:-5,energy:4,injury:.02,focus:'regularidade'},equilibrado:{label:'Equilibrado',scoreMod:0,energy:10,injury:.05,focus:'equilíbrio'},protagonista:{label:'Protagonista',scoreMod:6,energy:17,injury:.09,focus:'impacto'}};
const TALENTS = [
  {id:'visao-de-jogo',name:'Visão de Jogo',origin:'Kevin De Bruyne',attr:'visao',passive:'Passe sob pressão +10%',rarity:'Épico'},
  {id:'aceleracao-explosiva',name:'Aceleração Explosiva',origin:'Kylian Mbappé',attr:'ritmo',passive:'Arranque decisivo +12%',rarity:'Lendário'},
  {id:'drible-instintivo',name:'Drible Instintivo',origin:'Neymar',attr:'drible',passive:'Drible em 1x1 +12%',rarity:'Lendário'},
  {id:'finalizacao-fria',name:'Finalização Fria',origin:'Cristiano Ronaldo',attr:'finalizacao',passive:'Chance de gol +10%',rarity:'Lendário'},
  {id:'primeiro-toque',name:'Primeiro Toque Impossível',origin:'Lionel Messi',attr:'passe',passive:'Controle orientado +10%',rarity:'Lendário'},
  {id:'muralha',name:'Muralha',origin:'Manuel Neuer',attr:'reflexo',passive:'Defesas difíceis +12%',rarity:'Épico'},
  {id:'desarme-limpo',name:'Desarme Limpo',origin:'Virgil van Dijk',attr:'defesa',passive:'Duelo defensivo +12%',rarity:'Épico'}
];
const RIVALS = [
  {id:'lucas',name:'Lucas Vidal',club:'Academia Local',position:'Ponta',base:39,personality:'Provocador',talent:TALENTS[1]},
  {id:'gabriel',name:'Gabriel Rocha',club:'Academia Local',position:'Meia',base:45,personality:'Calculista',talent:TALENTS[0]},
  {id:'caio',name:'Caio Mendes',club:'Clube Profissional',position:'Atacante',base:55,personality:'Ambicioso',talent:TALENTS[3]},
  {id:'enzo',name:'Enzo Martins',club:'Clube Europeu',position:'Ponta',base:72,personality:'Confiante',talent:TALENTS[2]}
];
const MEDIA_LINES = ['“Ele não para de evoluir. Tem alguma coisa diferente aí.”','“O garoto entrou no jogo e mudou completamente o ritmo.”','“Os adversários já estão estudando seu nome.”','“De promessa desconhecida a assunto nacional em poucas semanas.”','“A torcida quer ver até onde esse fenômeno consegue chegar.”'];
let clubs=[]; let selectedPage='carreira'; let lastWeeklyStartOvr=null; let toastTimer=null;
function clamp(value,min,max){const n=Number(value);if(!Number.isFinite(n))return min;return Math.max(min,Math.min(max,n));}
function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function chance(p){return Math.random()<p;}
function formatMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Math.max(0,v));}
function uid(prefix='id'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;}
function deepClone(v){return JSON.parse(JSON.stringify(v));}
function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function calcOverall(state){const keys=Object.keys(ATTR_META);const valid=keys.filter(k=>Number.isFinite(state.player.attrs[k]));if(!valid.length)return 20;const base=valid.reduce((t,k)=>t+state.player.attrs[k],0)/valid.length;const posBonus=state.player.position==='Goleiro'?((state.player.attrs.reflexo-40)*.2):((state.player.attrs.finalizacao+state.player.attrs.drible-80)*.03);const talentBonus=state.player.talents.filter(t=>t.complete).length*1.8;return Math.round(clamp(base+posBonus+talentBonus,1,99));}
function categoryIndex(name){const i=CATEGORY_RULES.findIndex(c=>c.name===name);return Math.max(0,i);}
function createFreshState(){const attrs={ritmo:24,fisico:23,finalizacao:22,passe:25,drible:26,visao:24,mental:21,defesa:21,reflexo:20};const potential=Object.fromEntries(Object.keys(attrs).map(k=>[k,80]));return{version:VERSION,createdAt:Date.now(),difficulty:'normal',player:{name:'Isaac',age:15,position:'Ponta',category:'Sub-15',club:'Academia Local',salary:0,loyalty:55,morale:72,form:68,energy:100,fatigue:0,injuredWeeks:0,attrs,potential,talents:[],copies:8,systemLevel:1,copyUsed:0,personality:{ambition:55,ego:45,discipline:55,leadership:35,coldBlood:45,popularity:5}},career:{season:1,week:1,phase:'Pré-temporada',trainingsUsed:0,matches:0,wins:0,draws:0,losses:0,goals:0,assists:0,decisive:0,titles:0,value:1000,clubReputation:20,trophies:[],records:[],history:[],totalSeasons:0},clubState:{tactic:'equilibrado',chemistry:55,managerTrust:45,starterChance:48},contract:{duration:0,yearsLeft:0,releaseClause:0,agent:'Conservador'},market:{offers:[],windowOpen:true,interest:[]},rivals:RIVALS.map(r=>({...deepClone(r),relationship:0,winsAgainstPlayer:0,lossesAgainstPlayer:0})),achievements:[],notifications:[],log:['[ SISTEMA ] O estádio está vazio. Uma janela azul aparece diante dos seus olhos.','[ SISTEMA ] Roubo de Talento desbloqueado.']};}
let state=createFreshState();
function normalizeState(raw){const fresh=createFreshState();if(!raw||typeof raw!=='object')return fresh;const merged={...fresh,...raw,player:{...fresh.player,...(raw.player||{})},career:{...fresh.career,...(raw.career||{})},clubState:{...fresh.clubState,...(raw.clubState||{})},contract:{...fresh.contract,...(raw.contract||{})},market:{...fresh.market,...(raw.market||{})}};merged.player.attrs={...fresh.player.attrs,...(raw.player?.attrs||{})};merged.player.potential={...fresh.player.potential,...(raw.player?.potential||{})};merged.player.talents=Array.isArray(raw.player?.talents)?raw.player.talents:[];merged.rivals=Array.isArray(raw.rivals)?raw.rivals:fresh.rivals;merged.achievements=Array.isArray(raw.achievements)?raw.achievements:[];merged.notifications=Array.isArray(raw.notifications)?raw.notifications.slice(0,50):[];merged.log=Array.isArray(raw.log)?raw.log.slice(-40):fresh.log;merged.player.age=clamp(merged.player.age,15,45);merged.player.copies=clamp(merged.player.copies,0,999);merged.player.systemLevel=clamp(merged.player.systemLevel,1,99);merged.player.energy=clamp(merged.player.energy,0,100);merged.player.fatigue=clamp(merged.player.fatigue,0,100);merged.player.morale=clamp(merged.player.morale,0,100);merged.player.form=clamp(merged.player.form,0,100);merged.player.loyalty=clamp(merged.player.loyalty,0,100);for(const k of Object.keys(fresh.player.attrs)){merged.player.attrs[k]=clamp(merged.player.attrs[k],1,99);merged.player.potential[k]=clamp(merged.player.potential[k],1,99);}return merged;}
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{}}
function loadSave(){try{const text=localStorage.getItem(SAVE_KEY);if(text)state=normalizeState(JSON.parse(text));}catch{state=createFreshState();notify('SAVE','Não foi possível ler o save antigo. Uma carreira nova foi carregada.');}}
function resetSave(){state=createFreshState();lastWeeklyStartOvr=null;persist();renderAll();notify('NOVO JOGO','Uma nova carreira foi iniciada.');}
function log(message,tone=''){state.log.push((tone?`[${tone}] `:'')+message);state.log=state.log.slice(-40);}
function notify(title,message){const box=document.getElementById('toast');if(!box)return;box.innerHTML=`<b>${esc(title)}</b><span>${esc(message)}</span>`;box.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('show'),3600);}
function addNotification(title,body,type='system'){state.notifications.unshift({id:uid('note'),title,body,type,at:Date.now()});state.notifications=state.notifications.slice(0,50);notify(title,body);}
function earnAchievement(id,title,description){if(state.achievements.some(a=>a.id===id))return;state.achievements.push({id,title,description,at:Date.now()});addNotification('CONQUISTA',title,'achievement');}
function nextOpponent(){const tier=categoryIndex(state.player.category);const base=RIVALS[Math.min(RIVALS.length-1,(state.career.week-1+tier)%RIVALS.length)];const growth=Math.max(0,state.career.season-1)*2+Math.floor(state.career.week/4);return{...base,base:base.base+growth};}
function duelChance(opponent){const diff=calcOverall(state)-opponent.base;const energyFactor=state.player.energy<35?-12:state.player.energy<60?-5:0;const moraleFactor=(state.player.morale-50)*.12;const formFactor=(state.player.form-50)*.16;const rivalryFactor=(state.rivals.find(r=>r.id===opponent.id)?.relationship||0)*.05;const difficultyFactor=state.difficulty==='sss'?-6:0;return clamp(Math.round(42+diff*1.4+energyFactor+moraleFactor+formFactor+rivalryFactor+difficultyFactor),6,92);}
function findTalentById(id){return state.player.talents.find(t=>t.id===id);}
function attemptDuel(){if(state.player.injuredWeeks>0)return notify('INDISPONÍVEL','Você está lesionado e não pode disputar o duelo.');if(state.player.energy<25)return notify('ENERGIA BAIXA','Descanse antes de buscar outro talento.');const opponent=nextOpponent();if(state.player.copies<=0)return notify('SEM CÓPIAS','Você ficou sem Pontos de Cópia.');const chancePct=duelChance(opponent);state.player.copies-=1;state.player.copyUsed+=1;state.player.energy=clamp(state.player.energy-14,0,100);const success=Math.random()*100<chancePct;const rival=state.rivals.find(r=>r.id===opponent.id);if(success){if(rival){rival.relationship-=5;rival.lossesAgainstPlayer+=1;}let talent=findTalentById(opponent.talent.id);if(!talent){talent={...deepClone(opponent.talent),fragments:0,complete:false,level:1,awakened:false,stolenAt:Date.now()};state.player.talents.push(talent);}talent.fragments=clamp((talent.fragments||0)+1,0,3);if(talent.fragments>=3&&!talent.complete){talent.complete=true;state.player.potential[talent.attr]=99;state.player.systemLevel=clamp(state.player.systemLevel+1,1,99);addNotification('HABILIDADE ADQUIRIDA',`${talent.name} está completa. Teto de ${ATTR_META[talent.attr].label} = 99.`,'talent');earnAchievement(`talent-${talent.id}`,`Talento completo: ${talent.name}`,'Fragmentos 3/3 e passiva permanente desbloqueada.');log(`${talent.name} completa. A passiva foi incorporada ao Sistema.`,'SISTEMA');}else{addNotification('FRAGMENTO ROUBADO',`${talent.name}: ${talent.fragments}/3.`,'talent');log(`Fragmento de ${talent.name} roubado de ${talent.origin}.`,'SISTEMA');}state.player.form=clamp(state.player.form+4,0,100);}else{if(rival){rival.relationship+=4;rival.winsAgainstPlayer+=1;}state.player.morale=clamp(state.player.morale-3,0,100);log(`Duelo perdido contra ${opponent.name}. O talento ${opponent.talent.name} continua fora do alcance.`,'FALHA');notify('DUELO PERDIDO',`Chance calculada ${chancePct}%. Treine, descanse e tente novamente.`);}persist();renderAll();}
function focusedAttribute(position,trainingKey){const posMap={Atacante:['finalizacao','ritmo','mental'],Ponta:['drible','ritmo','passe'],Meia:['passe','visao','mental'],Volante:['defesa','fisico','passe'],Zagueiro:['defesa','fisico','mental'],Goleiro:['reflexo','fisico','mental']};const pool=posMap[position]||posMap.Ponta;if(trainingKey==='físico')return pool.includes('fisico')?'fisico':pool[0];if(trainingKey==='mental')return pool.includes('mental')?'mental':pool[1];return pool[rand(0,pool.length-1)];}
function train(type){if(state.player.injuredWeeks>0)return notify('LESIONADO','Você precisa se recuperar antes de treinar.');if(state.career.trainingsUsed>=WEEK_LIMIT)return notify('LIMITE ATINGIDO',`Você já fez ${WEEK_LIMIT} sessões nesta semana.`);const spec=TRAINING[type];if(!spec)return;if(state.player.energy<spec.cost)return notify('ENERGIA INSUFICIENTE','Descanse e administre a semana.');state.career.trainingsUsed+=1;state.player.energy=clamp(state.player.energy-spec.cost,0,100);const beforeOvr=calcOverall(state);const success=chance(spec.chance);if(success){const attr=focusedAttribute(state.player.position,spec.focus);if(state.player.attrs[attr]>=state.player.potential[attr]){state.player.morale=clamp(state.player.morale+1,0,100);log(`${spec.label}: ${ATTR_META[attr].label} já atingiu o teto ${state.player.potential[attr]}.`,'TREINO');}else{const gain=rand(spec.gain[0],spec.gain[1]);const old=state.player.attrs[attr];state.player.attrs[attr]=clamp(Math.min(state.player.potential[attr],old+gain),1,99);const actual=state.player.attrs[attr]-old;state.player.form=clamp(state.player.form+(actual>0?2:0),0,100);log(`${spec.label}: +${actual} ${ATTR_META[attr].label}.`,'TREINO');}state.player.fatigue=clamp(state.player.fatigue+spec.fatigue,0,100);}else{state.player.morale=clamp(state.player.morale-(type==='espartano'?5:2),0,100);state.player.form=clamp(state.player.form-1,0,100);log(`${spec.label}: sessão falhou. Sem ganho de atributo.`,'FALHA');}if(chance(spec.injury)){state.player.injuredWeeks=rand(1,type==='espartano'?3:1);state.player.energy=10;addNotification('LESÃO',`Você ficará fora por ${state.player.injuredWeeks} semana(s).`,'injury');}const afterOvr=calcOverall(state);if(afterOvr-beforeOvr>=5)suddenRiseEvent(beforeOvr,afterOvr);persist();renderAll();}
function suddenRiseEvent(before,after){addNotification('REAÇÃO DO VESTIÁRIO',`Seu overall saltou de ${before} para ${after}. Começam os rumores.`,'story');state.player.personality.popularity=clamp(state.player.personality.popularity+2,0,100);state.career.clubReputation=clamp(state.career.clubReputation+3,0,100);log(MEDIA_LINES[rand(0,MEDIA_LINES.length-1)],'MÍDIA');}
function applyMatchRewards(result,approach){state.career.matches+=1;if(result.outcome==='win')state.career.wins+=1;else if(result.outcome==='draw')state.career.draws+=1;else state.career.losses+=1;state.career.goals+=result.goals;state.career.assists+=result.assists;if(result.dec)state.career.decisive+=1;state.player.energy=clamp(state.player.energy-approach.energy,0,100);state.player.fatigue=clamp(state.player.fatigue+Math.round(approach.energy*1.2),0,100);state.player.form=clamp(state.player.form+(result.rating>=7?5:result.rating>=6?2:-4),0,100);state.player.morale=clamp(state.player.morale+(result.outcome==='win'?4:result.outcome==='loss'?-4:1),0,100);state.player.personality.popularity=clamp(state.player.personality.popularity+(result.dec?2:result.goals?1:0),0,100);state.career.value=Math.round(state.career.value*(1+(result.rating-6)*.035)+result.goals*6000+result.assists*2500);if(result.outcome==='win'&&result.dec)earnAchievement('decisive-1','Homem do jogo','Decidiu uma partida com gol ou assistência.');log(`Partida: ${result.outcome==='win'?'vitória':result.outcome==='draw'?'empate':'derrota'} ${result.gf}–${result.ga}. Nota ${result.rating.toFixed(1)}.`,'PARTIDA');}
function simulateMatch(approachKey){if(state.player.injuredWeeks>0)return notify('LESIONADO','Você não pode jogar nesta semana.');const approach=APPROACHES[approachKey];if(!approach)return;if(state.player.energy<20)return notify('SEM ENERGIA','Você precisa descansar antes da partida.');const ovr=calcOverall(state);const opponent=Math.round(ovr+rand(-8,10)+(categoryIndex(state.player.category)*3)-4);const tactic=state.clubState.tactic==='ofensivo'?4:state.clubState.tactic==='defensivo'?-3:0;const form=(state.player.form-50)*.12;const morale=(state.player.morale-50)*.08;const chemistry=(state.clubState.chemistry-50)*.06;const noise=rand(-10,10);const performance=ovr-opponent+tactic+form+morale+chemistry+approach.scoreMod+noise;const outcome=performance>=7?'win':performance<=-7?'loss':'draw';const baseGF=outcome==='win'?rand(1,3):outcome==='draw'?rand(0,2):rand(0,1);const baseGA=outcome==='win'?rand(0,1):outcome==='draw'?baseGF:rand(1,3);const impactChance=clamp(.15+ovr/500+state.player.talents.filter(t=>t.complete).length*.05,.1,.75);const involved=chance(impactChance);const goals=involved&&state.player.position!=='Goleiro'&&chance(.42)?1:0;const assists=involved&&chance(.33)?1:0;const rating=clamp(5.2+performance*.09+(goals?1.2:0)+(assists?.7:0)+(state.player.energy>70?.25:0),3,10);const result={outcome,gf:Math.max(baseGF+goals,0),ga:Math.max(baseGA,0),goals,assists,rating,dec:goals>0||assists>0};if(result.gf===result.ga&&result.outcome==='loss')result.ga+=1;applyMatchRewards(result,approach);if(chance(approach.injury+state.player.fatigue/1000)){state.player.injuredWeeks=rand(1,approachKey==='protagonista'?3:2);addNotification('LESÃO',`Choque na partida. Fora por ${state.player.injuredWeeks} semana(s).`,'injury');}persist();renderAll();}
function endWeek(){if(state.career.week>=10)return endSeason();state.career.week+=1;state.career.phase=state.career.week<=2?'Pré-temporada':'Rodadas';state.career.trainingsUsed=0;state.player.energy=clamp(state.player.energy+38-Math.round(state.player.fatigue*.3),0,100);state.player.fatigue=clamp(state.player.fatigue-20,0,100);state.player.form=clamp(state.player.form+1,0,100);if(state.player.injuredWeeks>0)state.player.injuredWeeks-=1;const before=lastWeeklyStartOvr??calcOverall(state);const after=calcOverall(state);if(after-before>=10)suddenRiseEvent(before,after);lastWeeklyStartOvr=after;if(state.career.week===5||state.career.week===8)generateOffers();log(`Semana ${state.career.week}: Sistema recalibrado. Energia ${state.player.energy}%.`,'SISTEMA');persist();renderAll();}
function endSeason(){const ovr=calcOverall(state);state.career.totalSeasons+=1;state.player.age+=1;state.career.week=1;state.career.phase='Pré-temporada';state.career.trainingsUsed=0;state.player.injuredWeeks=0;state.player.energy=100;state.player.fatigue=0;state.player.form=clamp(state.player.form+4,0,100);state.market.windowOpen=true;if(state.player.age>=31){for(const k of Object.keys(state.player.attrs))if(PHYSICAL.has(k))state.player.attrs[k]=clamp(state.player.attrs[k]-rand(2,4),1,99);log('A idade começa a cobrar seu preço físico. Talentos técnicos e mentais permanecem intactos.','IDADE');}const promo=tryPromotion();if(state.career.wins>=6&&state.career.goals>=8){state.career.titles+=1;state.career.trophies.push(`Temporada ${state.career.season} — Troféu de Elite`);earnAchievement(`title-${state.career.season}`,'Temporada campeã','A equipe terminou a temporada no topo.');}state.career.season+=1;state.career.wins=0;state.career.draws=0;state.career.losses=0;state.career.goals=0;state.career.assists=0;state.career.decisive=0;if(!state.contract.yearsLeft)proposeContract();addNotification('FIM DE TEMPORADA',`Você chegou ao ${state.player.age}º ano com OVR ${ovr}.${promo?` Promoção: ${promo}.`:''}`,'story');persist();renderAll();}
function tryPromotion(){const currentIdx=categoryIndex(state.player.category);const next=CATEGORY_RULES[currentIdx+1];if(!next)return null;if(calcOverall(state)>=next.minOvr&&state.player.age>=next.minAge){state.player.category=next.name;state.player.club=next.club;state.career.clubReputation=clamp(state.career.clubReputation+12,0,100);earnAchievement(`promo-${next.name}`,`Promoção para ${next.name}`,`Você atingiu ${next.minOvr}+ de overall e avançou de categoria.`);log(`TRANSIÇÃO: ${next.name} desbloqueada.`,'SISTEMA');return next.name;}return null;}
function generateOffers(){if(!state.market.windowOpen)return;const tier=categoryIndex(state.player.category);const ovr=calcOverall(state);const names=tier>=3?['Real Madrid','Manchester City','Barcelona','Liverpool']:tier>=2?['Palmeiras','Flamengo','São Paulo','Atlético Mineiro']:['ABC Futebol Clube','Sport','Bahia','Fortaleza'];state.market.offers=names.slice(0,3).map((club,i)=>({id:uid('offer'),club,salary:Math.max(0,Math.round(ovr*(1400+i*350)*(1+state.player.personality.popularity/200))),years:2+i%2,clause:Math.round(ovr*85000*(i+1)),role:i===0?'Titular em disputa':i===1?'Rotação':'Projeto de estrela'}));addNotification('MERCADO',`${state.market.offers.length} clubes demonstraram interesse.`,'market');}
function proposeContract(){const agentFactor=state.contract.agent==='Agressivo'?1.18:.98;state.contract.duration=3;state.contract.yearsLeft=3;state.player.salary=Math.round(Math.max(1500,calcOverall(state)*1600)*agentFactor);state.contract.releaseClause=Math.round(Math.max(100000,state.player.salary*36));log(`Novo contrato: ${formatMoney(state.player.salary)}/mês, ${state.contract.yearsLeft} anos.`,'MERCADO');}
function acceptOffer(id){const offer=state.market.offers.find(o=>o.id===id);if(!offer)return;state.player.club=offer.club;state.player.salary=offer.salary;state.contract.duration=offer.years;state.contract.yearsLeft=offer.years;state.contract.releaseClause=offer.clause;state.market.offers=[];state.player.loyalty=clamp(state.player.loyalty-12,0,100);state.career.clubReputation=clamp(state.career.clubReputation+7,0,100);addNotification('TRANSFERÊNCIA',`Você assinou com ${offer.club}. ${formatMoney(offer.salary)}/mês.`,'market');persist();renderAll();}
function rejectOffer(id){state.market.offers=state.market.offers.filter(o=>o.id!==id);state.player.loyalty=clamp(state.player.loyalty+2,0,100);persist();renderAll();}
function chooseAgent(agent){if(!['Agressivo','Conservador'].includes(agent))return;state.contract.agent=agent;persist();renderAll();}
function setTactic(tactic){if(!['ofensivo','equilibrado','defensivo'].includes(tactic))return;state.clubState.tactic=tactic;persist();renderAll();}
function changePosition(pos){if(!POSITIONS.includes(pos))return;state.player.position=pos;persist();renderAll();}
function chooseDifficulty(level){if(!['normal','sss'].includes(level))return;state.difficulty=level;state.player.copies=level==='sss'?Math.min(state.player.copies,5):Math.max(state.player.copies,8);persist();renderAll();}
function dailyRecovery(){state.player.energy=clamp(state.player.energy+22,0,100);state.player.fatigue=clamp(state.player.fatigue-18,0,100);state.player.morale=clamp(state.player.morale+2,0,100);persist();renderAll();}
function newGamePlus(){if(state.career.totalSeasons<5&&calcOverall(state)<84)return notify('DESBLOQUEIO','New Game+ exige 5 temporadas ou overall 84.');const carry=state.player.talents.filter(t=>t.complete).map(t=>({...deepClone(t),fragments:3,complete:true,level:1}));state=createFreshState();state.player.name='Novo Craque';state.player.talents=carry;state.player.copies=10+carry.length;state.player.systemLevel=1+carry.length;for(const t of carry)state.player.potential[t.attr]=99;addNotification('NEW GAME+','Uma nova linha do tempo começou com sua coleção permanente.','achievement');persist();renderAll();}
function renderTop(){document.getElementById('copyTop').textContent=state.player.copies;document.getElementById('season').textContent=String(state.career.season).padStart(2,'0');document.getElementById('week').textContent=state.career.week;document.getElementById('phase').textContent=state.career.phase;}
function renderCareer(){const opponent=nextOpponent();const chancePct=duelChance(opponent);document.getElementById('headline').textContent=state.player.age<=16?'O começo do Sistema':`A ascensão de ${state.player.name}`;document.getElementById('subheadline').textContent=state.player.injuredWeeks?`Lesionado por ${state.player.injuredWeeks} semana(s). A carreira também se constrói fora do campo.`:MEDIA_LINES[(state.career.week+state.career.season)%MEDIA_LINES.length];document.getElementById('name').textContent=state.player.name;document.getElementById('position').value=state.player.position;document.getElementById('category').textContent=state.player.category;document.getElementById('age').textContent=state.player.age;document.getElementById('club').textContent=state.player.club;document.getElementById('ovr').textContent=calcOverall(state);document.getElementById('energy').textContent=`${state.player.energy}%`;document.getElementById('morale').textContent=`${state.player.morale}%`;document.getElementById('form').textContent=`${state.player.form}%`;document.getElementById('fatigue').textContent=`${state.player.fatigue}%`;document.getElementById('salary').textContent=formatMoney(state.player.salary);document.getElementById('value').textContent=formatMoney(state.career.value);document.getElementById('loyalty').textContent=`${state.player.loyalty}%`;document.getElementById('trophies').textContent=state.career.trophies.length;document.getElementById('starterChance').textContent=`${state.clubState.starterChance}%`;document.getElementById('trust').textContent=`${state.clubState.managerTrust}%`;document.getElementById('record').textContent=`${state.career.wins}V ${state.career.draws}E ${state.career.losses}D`;document.getElementById('nextOpponent').textContent=opponent.name;document.getElementById('opponentOvr').textContent=opponent.base;document.getElementById('targetTalent').textContent=opponent.talent.name;document.getElementById('duelChance').textContent=`${chancePct}%`;document.getElementById('duelBar').style.width=`${chancePct}%`;document.getElementById('trainCount').textContent=`${WEEK_LIMIT-state.career.trainingsUsed}/${WEEK_LIMIT} sessões disponíveis`;document.getElementById('injuryStatus').textContent=state.player.injuredWeeks?`Fora ${state.player.injuredWeeks} sem.`:'Apto';document.getElementById('contractYears').textContent=state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato';document.getElementById('agent').textContent=state.contract.agent;document.getElementById('clause').textContent=formatMoney(state.contract.releaseClause);document.querySelectorAll('[data-action="match"]').forEach(b=>b.disabled=state.player.injuredWeeks>0||state.player.energy<20);document.getElementById('duelBtn').disabled=state.player.copies<1||state.player.injuredWeeks>0||state.player.energy<25);renderAttrs();renderTalents();renderLog();renderCareerHistory();}
function renderAttrs(){document.getElementById('attrs').innerHTML=Object.entries(ATTR_META).map(([key,meta])=>{const current=clamp(state.player.attrs[key],0,99);const pot=clamp(state.player.potential[key],1,99);return`<div class="attr-row"><div><span>${esc(meta.label)}</span><small>${esc(meta.group)}</small></div><div class="bar"><i style="width:${current}%"></i></div><strong>${current}</strong><small class="pot">${pot===99?'◆ 99':`Teto ${pot}`}</small></div>`;}).join('');}
function renderTalents(){const root=document.getElementById('talents');if(!state.player.talents.length){root.innerHTML='<div class="empty">Nenhum talento coletado. Os primeiros duelos estão à espera.</div>';return;}root.innerHTML=state.player.talents.map(t=>`<article class="talent-card ${t.complete?'complete':''}"><div class="talent-gem">✦</div><div><b>${esc(t.name)}</b><small>${esc(t.origin)} • ${t.fragments}/3 • ${esc(t.rarity)}</small><small>${t.complete?`PASSIVA: ${esc(t.passive)}`:`Atributo: ${esc(ATTR_META[t.attr]?.label||t.attr)}`}</small></div><strong>${t.complete?'SSS':`${t.fragments}/3`}</strong></article>`).join('');}
function renderLog(){document.getElementById('log').innerHTML=state.log.slice(-7).map(line=>`<div>${esc(line)}</div>`).join('');}
function renderCareerHistory(){const root=document.getElementById('history');const items=state.notifications.slice(0,6);root.innerHTML=items.length?items.map(n=>`<div class="history-item"><b>${esc(n.title)}</b><span>${esc(n.body)}</span></div>`).join(''):'<div class="empty">Ainda não há eventos.</div>';}
function renderTraining(){document.getElementById('trainingStatus').textContent=`Energia ${state.player.energy}% • Fadiga ${state.player.fatigue}% • ${WEEK_LIMIT-state.career.trainingsUsed} sessões restantes`;document.querySelectorAll('[data-train]').forEach(btn=>btn.disabled=state.career.trainingsUsed>=WEEK_LIMIT||state.player.injuredWeeks>0);}
function renderMarket(){const root=document.getElementById('offers');if(!state.market.offers.length)root.innerHTML='<div class="empty">Nenhuma proposta agora. As janelas de mercado aparecem durante a temporada.</div>';else root.innerHTML=state.market.offers.map(o=>`<article class="offer-card"><div><b>${esc(o.club)}</b><span>${esc(o.role)}</span></div><strong>${formatMoney(o.salary)}<small>/mês</small></strong><div class="offer-meta"><span>${o.years} anos</span><span>cláusula ${formatMoney(o.clause)}</span></div><div class="actions"><button class="btn primary" data-offer="accept" data-id="${esc(o.id)}">Assinar</button><button class="btn" data-offer="reject" data-id="${esc(o.id)}">Recusar</button></div></article>`).join('');document.getElementById('agentAgg').classList.toggle('active',state.contract.agent==='Agressivo');document.getElementById('agentCons').classList.toggle('active',state.contract.agent==='Conservador');document.getElementById('loyaltyMarket').textContent=`${state.player.loyalty}%`;}
function renderClubs(){const term=(document.getElementById('clubSearch')?.value||'').trim().toLowerCase();const country=document.getElementById('clubCountry')?.value||'';const sort=document.getElementById('clubSort')?.value||'rel';let list=clubs.filter(c=>{const text=[c.name,c.city,c.state,c.country,c.short_name,...(c.aliases||[])].join(' ').toLowerCase();return(!term||text.includes(term))&&(!country||c.country===country);});list.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'pt-BR'):(b.relevance||0)-(a.relevance||0)||a.name.localeCompare(b.name,'pt-BR'));document.getElementById('clubCount').textContent=`${list.length.toLocaleString('pt-BR')} clubes`;document.getElementById('clubList').innerHTML=list.slice(0,300).map(c=>`<article class="club-card"><b>${esc(c.short_name||c.name)}</b><span>${esc(c.name)}</span><small>${esc(c.city||'')}${c.state?` • ${esc(c.state)}`:''}<br>${esc(c.country||'')}</small><em>RELEVÂNCIA ${clamp(c.relevance||0,0,100)}</em></article>`).join('')||'<div class="empty">Nenhum clube encontrado.</div>';}
function populateCountries(){const select=document.getElementById('clubCountry');const countries=[...new Set(clubs.map(c=>c.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));select.innerHTML='<option value="">Todos os países</option>'+countries.map(c=>`<option>${esc(c)}</option>`).join('');}
function renderSystem(){document.getElementById('systemLevel').textContent=state.player.systemLevel;document.getElementById('copiesUsed').textContent=state.player.copyUsed;document.getElementById('difficulty').value=state.difficulty;document.getElementById('position').value=state.player.position;document.getElementById('ngpBtn').disabled=!(state.career.totalSeasons>=5||calcOverall(state)>=84);document.getElementById('achievements').innerHTML=state.achievements.length?state.achievements.map(a=>`<div class="achievement"><b>${esc(a.title)}</b><span>${esc(a.description)}</span></div>`).join(''):'<div class="empty">Conquistas começam com a primeira decisão.</div>';}
function renderAll(){renderTop();renderCareer();renderTraining();renderMarket();renderClubs();renderSystem();applyPageVisibility();}
function applyPageVisibility(){document.querySelectorAll('[data-page]').forEach(btn=>btn.classList.toggle('active',btn.dataset.page===selectedPage));document.querySelectorAll('.page').forEach(page=>page.classList.toggle('active',page.id===`page-${selectedPage}`));}
function setPage(page){if(!['carreira','treino','mercado','clubes','sistema'].includes(page))return;selectedPage=page;applyPageVisibility();}
function bindEvents(){document.addEventListener('click',event=>{const page=event.target.closest('[data-page]');if(page)return setPage(page.dataset.page);const trainBtn=event.target.closest('[data-train]');if(trainBtn)return train(trainBtn.dataset.train);const matchBtn=event.target.closest('[data-action="match"]');if(matchBtn)return simulateMatch(matchBtn.dataset.approach);if(event.target.closest('#duelBtn'))return attemptDuel();if(event.target.closest('#weekBtn'))return endWeek();if(event.target.closest('#restBtn'))return dailyRecovery();const tactic=event.target.closest('[data-tactic]');if(tactic)return setTactic(tactic.dataset.tactic);const offer=event.target.closest('[data-offer]');if(offer)return offer.dataset.offer==='accept'?acceptOffer(offer.dataset.id):rejectOffer(offer.dataset.id);const agent=event.target.closest('[data-agent]');if(agent)return chooseAgent(agent.dataset.agent);if(event.target.closest('#saveBtn')){persist();return notify('SALVO','Sua carreira foi gravada neste dispositivo.');}if(event.target.closest('#newGameBtn'))return resetSave();if(event.target.closest('#ngpBtn'))return newGamePlus();});document.getElementById('clubSearch').addEventListener('input',renderClubs);document.getElementById('clubCountry').addEventListener('change',renderClubs);document.getElementById('clubSort').addEventListener('change',renderClubs);document.getElementById('position').addEventListener('change',e=>changePosition(e.target.value));document.getElementById('difficulty').addEventListener('change',e=>chooseDifficulty(e.target.value));}
async function loadClubs(){try{const response=await fetch('data/clubs.generated.json',{cache:'no-store'});if(!response.ok)throw new Error('clubs request failed');const data=await response.json();clubs=Array.isArray(data)?data:(data.clubs||[]);}catch{clubs=[{name:'ABC Futebol Clube',country:'Brasil',state:'RN',city:'Natal',relevance:54},{name:'Flamengo',country:'Brasil',state:'RJ',city:'Rio de Janeiro',relevance:95},{name:'Real Madrid',country:'Europa',relevance:92}];notify('CLUBES','O catálogo completo não carregou; o jogo está usando uma lista de segurança.');}populateCountries();renderClubs();}
function boot(){loadSave();bindEvents();loadClubs();lastWeeklyStartOvr=calcOverall(state);renderAll();}
boot();
