'use strict';
(() => {
const KEY='craque-sss-v6', START=1996, END=2026, MAX_TRAIN=3, CUP_YEARS=[1998,2002,2006,2010,2014,2018,2022,2026];
const ATTR={ritmo:'Ritmo',fisico:'Físico',finalizacao:'Finalização',passe:'Passe',drible:'Drible',visao:'Visão',mental:'Mental',defesa:'Defesa',reflexo:'Reflexo'};
const POS=['Atacante','Ponta','Meia','Volante','Zagueiro','Goleiro'];
const PHYS=new Set(['ritmo','fisico','reflexo']);
const COUNTRIES=[['Brasil','🇧🇷'],['Argentina','🇦🇷'],['Portugal','🇵🇹'],['França','🇫🇷'],['Espanha','🇪🇸'],['Itália','🇮🇹'],['Alemanha','🇩🇪'],['Inglaterra','🏴'],['Países Baixos','🇳🇱'],['Bélgica','🇧🇪'],['Croácia','🇭🇷'],['Uruguai','🇺🇾'],['Suécia','🇸🇪'],['Polônia','🇵🇱'],['Noruega','🇳🇴'],['Egito','🇪🇬'],['Senegal','🇸🇳'],['Nigéria','🇳🇬'],['Costa do Marfim','🇨🇮'],['Camarões','🇨🇲'],['Gana','🇬🇭'],['Colômbia','🇨🇴'],['Chile','🇨🇱'],['México','🇲🇽'],['Estados Unidos','🇺🇸'],['Canadá','🇨🇦'],['Japão','🇯🇵'],['Coreia do Sul','🇰🇷'],['Dinamarca','🇩🇰'],['Turquia','🇹🇷'],['Rússia','🇷🇺'],['República Tcheca','🇨🇿'],['Suíça','🇨🇭'],['Áustria','🇦🇹'],['Romênia','🇷🇴'],['Sérvia','🇷🇸'],['Paraguai','🇵🇾'],['Equador','🇪🇨'],['Peru','🇵🇪'],['Bolívia','🇧🇴'],['Marrocos','🇲🇦'],['Argélia','🇩🇿'],['Irlanda','🇮🇪'],['Escócia','🏴']];
const TRAIN={leve:{cost:16,p:1,gain:1},pesado:{cost:28,p:.5,gain:3},espartano:{cost:46,p:.2,gain:6}};
const TACTICS={seguro:-5,equilibrado:0,protagonista:6};
const RULES=[{name:'Sub-15',age:15,ovr:0},{name:'Sub-17',age:16,ovr:40},{name:'Estreante Profissional',age:17,ovr:55},{name:'Europa',age:18,ovr:72},{name:'Seleção Principal',age:19,ovr:84}];
let history={players:[]},clubs=[],page='carreira',saveTimer;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, pct=p=>Math.random()<p, clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Math.max(0,Math.round(v||0)));
const flag=n=>(COUNTRIES.find(c=>c[0]===n)?.[1]||'🌎');
function fresh(){const attrs={ritmo:24,fisico:23,finalizacao:22,passe:25,drible:26,visao:24,mental:21,defesa:21,reflexo:20};return{v:6,year:1996,week:1,player:{name:'Novo Craque',nationality:'Brasil',age:15,birthYear:1981,position:'Ponta',category:'Sub-15',club:'Academia Local',salary:0,energy:100,fatigue:0,morale:72,form:68,loyalty:55,injured:0,tempPenalty:0,tempPenaltyGames:0,attrs,potential:Object.fromEntries(Object.keys(attrs).map(k=>[k,80])),copies:8,system:1,retired:false},career:{season:1,train:0,matches:0,wins:0,draws:0,losses:0,goals:0,assists:0,titles:0,value:1000,record:[],history:[]},clubState:{tactic:'equilibrado',chemistry:55,trust:45},contract:{years:0,agent:'Conservador',clause:0},market:[],national:{called:false,caps:0,goals:0,titles:0,role:'Fora da convocação'},talents:[],notifications:[{t:'1996',b:'O Sistema despertou. O mundo ainda não sabe seu nome.'}],log:['[SISTEMA] 1996 — Linha do tempo sincronizada.']};}
let S=fresh();
function overall(){const a=Object.entries(S.player.attrs).map(([k,v])=>PHYS.has(k)?clamp(v-S.player.tempPenalty,1,99):v);let base=a.reduce((x,y)=>x+y,0)/a.length;if(S.player.position==='Goleiro')base+=(S.player.attrs.reflexo-40)*.18;else base+=(S.player.attrs.finalizacao+S.player.attrs.drible-80)*.035;return Math.round(clamp(base+S.talents.filter(t=>t.complete).length*1.6,1,99))}
function category(){let c='Sub-15';for(const r of RULES)if(S.player.age>=r.age&&overall()>=r.ovr)c=r.name;return c}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.v===6){S=x;S.player={...fresh().player,...x.player,attrs:{...fresh().player.attrs,...(x.player?.attrs||{})},potential:{...fresh().player.potential,...(x.player?.potential||{})}};S.career={...fresh().career,...(x.career||{})};S.clubState={...fresh().clubState,...(x.clubState||{})};S.contract={...fresh().contract,...(x.contract||{})};S.national={...fresh().national,...(x.national||{})};S.talents=Array.isArray(x.talents)?x.talents:[];S.notifications=Array.isArray(x.notifications)?x.notifications.slice(0,60):[];S.log=Array.isArray(x.log)?x.log.slice(-60):[]}}catch{S=fresh()}}
function toast(t,b){const e=$('#toast');e.innerHTML=`<b>${esc(t)}</b><span>${esc(b)}</span>`;e.classList.add('show');clearTimeout(saveTimer);saveTimer=setTimeout(()=>e.classList.remove('show'),3200)}
function note(t,b){S.notifications.unshift({t,b,year:S.year});S.notifications=S.notifications.slice(0,60);toast(t,b)}
function save(){persist();toast('SALVO','Carreira gravada neste dispositivo.')}
function activePlayers(y){return history.players.filter(p=>p.spans.some(s=>y>=s.from&&y<=s.to&&s.level==='profissional'))}
function clubOf(p,y){return p.spans.filter(s=>y>=s.from&&y<=s.to&&s.level==='profissional').map(s=>s.club).join(' / ')}
function talentAvailable(){const candidates=activePlayers(S.year).filter(p=>!S.talents.some(t=>t.id===p.talent.id&&t.complete));return candidates.sort((a,b)=>a.birthYear-b.birthYear||a.name.localeCompare(b.name))[0]}
function train(type){if(S.player.retired)return toast('APOSENTADO','Sua carreira terminou.');if(S.player.injured)return toast('LESIONADO',`Você está fora por ${S.player.injured} partida(s).`);if(S.career.train>=MAX_TRAIN)return toast('LIMITE SEMANAL','Você já usou 3 sessões nesta semana.');const q=TRAIN[type];if(!q)return;if(S.player.energy<q.cost)return toast('ENERGIA BAIXA','Você precisa descansar.');S.career.train++;S.player.energy-=q.cost;const keys=({Atacante:['finalizacao','ritmo','mental'],Ponta:['drible','ritmo','passe'],Meia:['passe','visao','mental'],Volante:['defesa','fisico','passe'],Zagueiro:['defesa','fisico','mental'],Goleiro:['reflexo','fisico','mental']})[S.player.position]||['drible','ritmo','passe'];const attr=keys[rnd(0,keys.length-1)];const before=overall();if(pct(q.p)){const gain=Math.min(q.gain,Math.max(0,S.player.potential[attr]-S.player.attrs[attr]));S.player.attrs[attr]+=gain;S.player.form=clamp(S.player.form+(gain>0?2:0),0,100);note('TREINO',gain?`+${gain} ${ATTR[attr]}.`:`${ATTR[attr]} já está no teto.`)}else{S.player.morale=clamp(S.player.morale-(type==='espartano'?5:2),0,100);note('TREINO FALHOU',`A sessão ${type} não gerou evolução.`)}if(type==='pesado'&&pct(.15)){S.player.tempPenalty=Math.max(S.player.tempPenalty,rnd(2,4));S.player.tempPenaltyGames=1;note('FADIGA FÍSICA',`- ${S.player.tempPenalty} nos atributos físicos pela próxima partida.`)}if(type==='espartano'&&pct(.25)){S.player.injured=rnd(3,10);S.player.energy=8;note('LESÃO GRAVE',`Você ficará fora por ${S.player.injured} partidas.`)}if(overall()-before>=5)note('REAÇÃO DO MUNDO',`Seu overall saltou de ${before} para ${overall()}.`);persist();render()}
function duel(){if(S.player.retired||S.player.injured)return toast('INDISPONÍVEL','Você não pode disputar este duelo agora.');if(S.player.copies<1)return toast('SEM PONTOS','Você não tem Pontos de Cópia.');if(S.player.energy<22)return toast('ENERGIA BAIXA','Recupere-se antes do duelo.');const p=talentAvailable();if(!p)return toast('SEM ALVO','Nenhum craque ativo disponível neste ano.');const o=clamp(36+Math.round((S.year-p.birthYear)*1.4),25,96),c=clamp(Math.round(45+(overall()-o)*1.45+(S.player.form-50)*.12-(S.player.copies<2?3:0)),8,92);S.player.copies--;S.player.energy=clamp(S.player.energy-13,0,100);if(pct(c/100)){let t=S.talents.find(x=>x.id===p.talent.id);if(!t){t={...p.talent,fragments:0,complete:false};S.talents.push(t)}t.fragments=clamp((t.fragments||0)+1,0,3);if(t.fragments===3&&!t.complete){t.complete=true;S.player.potential[p.talent.attribute]=99;S.player.system++;note('HABILIDADE ADQUIRIDA',`${t.name} completa. Origem: ${p.name}.`)}else note('FRAGMENTO ROUBADO',`${t.name}: ${t.fragments}/3 • ${p.name} (${clubOf(p,S.year)}).`);S.player.form=clamp(S.player.form+3,0,100)}else{S.player.morale=clamp(S.player.morale-3,0,100);note('DUELO PERDIDO',`Chance ${c}%. ${p.name} protegeu seu talento.`)}persist();render()}
function match(){if(S.player.retired)return toast('APOSENTADO','Não há partidas após a aposentadoria.');if(S.player.injured)return toast('LESIONADO',`Você está fora por ${S.player.injured} partidas.`);if(S.player.energy<18)return toast('SEM ENERGIA','Recupere-se antes da partida.');const opp=clamp(overall()+rnd(-8,10),20,96),perf=overall()-opp+TACTICS[S.clubState.tactic]+(S.player.form-50)*.12+(S.clubState.chemistry-50)*.05+rnd(-9,9),out=perf>=7?'V':perf<=-7?'D':'E';const g=S.player.position==='Goleiro'?0:(out==='V'?rnd(0,2):pct(.22)?1:0),a=pct(.23)&&g<2?1:0;S.career.matches++;if(out==='V')S.career.wins++;else if(out==='E')S.career.draws++;else S.career.losses++;S.career.goals+=g;S.career.assists+=a;S.career.value=Math.round(S.career.value*(1+(5+perf*.08-5.5)*.025)+g*6000+a*2500);const r=clamp(5.2+perf*.08+g*1.1+a*.7,3,10);S.player.energy=clamp(S.player.energy-(S.clubState.tactic==='seguro'?5:S.clubState.tactic==='protagonista'?17:10),0,100);S.player.fatigue=clamp(S.player.fatigue+8,0,100);S.player.form=clamp(S.player.form+(r>=7?4:r<5.5?-3:1),0,100);S.player.morale=clamp(S.player.morale+(out==='V'?4:out==='D'?-4:1),0,100);if(pct(.035+S.player.fatigue/1400)){S.player.injured=rnd(1,2);note('LESÃO NA PARTIDA',`Fora por ${S.player.injured} partidas.`)}note('PARTIDA',`${out==='V'?'Vitória':out==='E'?'Empate':'Derrota'} • nota ${r.toFixed(1)} • ${g}G/${a}A`);if(S.player.tempPenaltyGames){S.player.tempPenaltyGames--;if(!S.player.tempPenaltyGames)S.player.tempPenalty=0}persist();render()}
function callSelection(){if(S.player.age>=18&&overall()>=65&&S.player.form>=52){S.national.called=true;S.national.caps++;S.national.role=S.national.caps<=3?'Banco':'Rotação';note('SELEÇÃO NACIONAL',`${flag(S.player.nationality)} ${S.player.nationality}: convocado.`)}}
function worldCup(){const ok=S.player.age>=18&&overall()>=70&&S.player.form>=55;S.national.called=ok;S.national.role=ok?'Convocado para a Copa':'Fora da Copa';if(ok){S.national.titles+=(S.national.caps&&pct(.18)?1:0);note('COPA DO MUNDO',`${flag(S.player.nationality)} ${S.player.nationality}: você está na lista do torneio.`)}else note('COPA DO MUNDO','Você ainda não atingiu os critérios para a Copa desta edição.')}
function propose(){const agent=S.contract.agent==='Agressivo'?1.18:.98;S.contract.years=3;S.contract.clause=Math.max(100000,Math.round(S.player.salary*36));S.player.salary=Math.max(1500,Math.round(overall()*1600*agent))}
function generateOffers(){if(S.player.retired)return;const tier=category().includes('Europa')||category()==='Seleção Principal';const names=tier?['Real Madrid','Manchester City','Barcelona','Liverpool']:overall()>=50?['Palmeiras','Flamengo','São Paulo','Atlético Mineiro']:['ABC Futebol Clube','Sport','Bahia','Fortaleza'];S.market=names.slice(0,3).map((club,i)=>({club,salary:Math.round(Math.max(1800,overall()*(1200+i*260))*(1+S.player.loyalty/500)),years:2+(i%2),role:i===0?'Titular em disputa':i===1?'Rotação':'Projeto de estrela'}));note('MERCADO',`${S.market.length} clubes demonstraram interesse.`);persist();render()}
function acceptOffer(i){const o=S.market[i];if(!o)return;S.player.club=o.club;S.player.salary=o.salary;S.contract.years=o.years;S.contract.clause=Math.max(100000,Math.round(o.salary*36));S.market=[];S.player.loyalty=clamp(S.player.loyalty-12,0,100);note('TRANSFERÊNCIA',`Você assinou com ${o.club}. ${money(o.salary)}/mês.`);persist();render()}
function endWeek(){if(S.player.retired)return toast('APOSENTADO','A carreira terminou.');if(S.career.week>=10)return endSeason();S.career.week++;S.career.train=0;S.player.energy=clamp(S.player.energy+38-Math.round(S.player.fatigue*.28),0,100);S.player.fatigue=clamp(S.player.fatigue-20,0,100);if(S.player.injured)S.player.injured--;if(S.player.injured===0&&S.player.tempPenaltyGames===0)S.player.tempPenalty=0;S.player.form=clamp(S.player.form+1,0,100);if(S.career.week===7)callSelection();if(CUP_YEARS.includes(S.year)&&S.career.week===8)worldCup();persist();render()}
function endSeason(){if(S.player.retired)return;S.career.history.unshift({year:S.year,age:S.player.age,overall:overall(),club:S.player.club,goals:S.career.goals,assists:S.career.assists,wins:S.career.wins});S.career.history=S.career.history.slice(0,24);S.year++;S.career.season++;S.career.week=1;S.career.train=0;S.player.age++;S.player.energy=100;S.player.fatigue=0;S.player.injured=0;S.player.tempPenalty=0;S.player.tempPenaltyGames=0;if(S.contract.years>0)S.contract.years--;if(S.player.age>=31)for(const k of Object.keys(S.player.attrs))if(PHYS.has(k))S.player.attrs[k]=clamp(S.player.attrs[k]-rnd(2,4),1,99);S.player.category=category();if(S.player.age>=40){S.player.retired=true;note('APOSENTADORIA',`Aos ${S.player.age}, sua carreira chegou ao fim.`)}else{if(S.player.age>=17&&overall()>=48)generateOffers();note('NOVA TEMPORADA',`A linha do tempo avançou para ${Math.min(S.year,END)}.`)}persist();render()}
function renderTop(){if($('#year'))$('#year').textContent=Math.min(S.year,END);if($('#season'))$('#season').textContent=String(S.career.season).padStart(2,'0');if($('#week'))$('#week').textContent=S.career.week;$('#copyTop').textContent=S.player.copies;$('#topFlag').textContent=flag(S.player.nationality);$('#topNat').textContent=S.player.nationality;$('#retiredPill').classList.toggle('show',S.player.retired)}
function render(){renderTop();const o=overall();$('#playerName').textContent=S.player.name;$('#playerNat').textContent=`${flag(S.player.nationality)} ${S.player.nationality}`;$('#ovr').textContent=o;$('#age').textContent=S.player.age;$('#position').textContent=S.player.position;$('#category').textContent=S.player.category;$('#playerClub').textContent=S.player.club;$('#energy').textContent=`${S.player.energy}%`;$('#fatigue').textContent=`${S.player.fatigue}%`;$('#morale').textContent=`${S.player.morale}%`;$('#form').textContent=`${S.player.form}%`;$('#salary').textContent=money(S.player.salary);$('#marketValue').textContent=money(S.career.value);$('#matchStatus').textContent=S.player.injured?`Fora ${S.player.injured} partidas.`:'Apto';const ta=talentAvailable();$('#duelChance').textContent=ta?`${clamp(Math.round(45+(o-36)*1.45),8,92)}%`:'—';$('#clubState').textContent=S.clubState.tactic;$('#record').textContent=`${S.career.wins}V ${S.career.draws}E ${S.career.losses}D`;$('#historyLog').innerHTML=S.notifications.slice(0,7).map(n=>`<div class="notice-line"><b>${esc(n.t)}</b><span>${esc(n.b)}</span></div>`).join('')||'<div class="empty">Sem eventos.</div>';renderAttrs();renderTalents();renderTrain();renderSel();renderWorld();renderClubs();renderMarket();renderSystem();applyPage()}
function renderAttrs(){if(!$('#attrs'))return;$('#attrs').innerHTML=Object.entries(ATTR).map(([k,v])=>{const n=PHYS.has(k)?clamp(S.player.attrs[k]-S.player.tempPenalty,1,99):S.player.attrs[k];return`<div class="attr"><div><span>${v}</span><small>Teto ${S.player.potential[k]}${PHYS.has(k)&&S.player.tempPenalty?' • temporário':''}</small></div><div class="bar"><i style="width:${n}%"></i></div><b>${n}</b></div>`}).join('')}
function renderTalents(){const e=$('#talents'),arr=S.talents||[];e.innerHTML=arr.length?arr.map(t=>`<article class="talent ${t.complete?'complete':''}"><div class="gem">✦</div><div><b>${esc(t.name)}</b><small>${t.fragments}/3 • ${t.complete?'PASSIVA PERMANENTE':esc(t.origin||'Craque da época')}</small></div><strong>${t.complete?'SSS':`${t.fragments}/3`}</strong></article>`).join(''):'<div class="empty">Nenhum talento coletado ainda.</div>'}
function renderTrain(){if($('#trainRemain'))$('#trainRemain').textContent=`${MAX_TRAIN-S.career.train}/${MAX_TRAIN} sessões`;$$('[data-train]').forEach(b=>b.disabled=S.player.injured>0||S.player.retired||S.career.train>=MAX_TRAIN)}
function renderSel(){const e=S.player.age>=18&&overall()>=65;$('#nationalFlag').textContent=flag(S.player.nationality);$('#nationalName').textContent=`Seleção ${S.player.nationality}`;$('#nationalName2').textContent=`Seleção ${S.player.nationality}`;$('#nationalRole').textContent=S.national.role;$('#nationalCaps').textContent=S.national.caps;$('#nationalOvr').textContent=clamp(50+overall()/2,50,99).toFixed(0);$('#selectionStatus').textContent=e?'Você está no radar da seleção.':'Ainda não atende aos critérios.';$('#nextCup').textContent=CUP_YEARS.find(y=>y>=S.year)||2030}
function renderWorld(){if(!history.players.length)return;const y=clamp(Number($('#historyYear')?.value||START),START,END);const term=($('#historySearch')?.value||'').toLowerCase();const arr=activePlayers(y).filter(p=>!term||p.name.toLowerCase().includes(term)||p.nationality.toLowerCase().includes(term)||clubOf(p,y).toLowerCase().includes(term));if($('#historyYear'))$('#historyYear').value=y;if($('#historyYearLabel'))$('#historyYearLabel').textContent=y;if($('#historyCount'))$('#historyCount').textContent=arr.length;if($('#historyPlayers'))$('#historyPlayers').innerHTML=arr.map(p=>`<article class="history-card"><div class="history-avatar">${flag(p.nationality)}</div><div><b>${esc(p.name)}</b><small>${esc(p.position)} • ${esc(p.nationality)} • nasceu em ${p.birthYear}</small><strong>${esc(clubOf(p,y))}</strong><em>${esc(p.talent.name)}</em></div></article>`).join('')||'<div class="empty">Nenhum craque profissional encontrado neste ano.</div>';$$('#historyYears .year-chip').forEach(b=>b.classList.toggle('active',Number(b.dataset.year)===y))}
function renderClubs(){const term=($('#clubSearch')?.value||'').toLowerCase();const country=$('#clubCountry')?.value||'';const sort=$('#clubSort')?.value||'rel';let arr=clubs.filter(c=>{const text=[c.name,c.city,c.state,c.country,c.short_name,...(c.aliases||[])].join(' ').toLowerCase();return(!term||text.includes(term))&&(!country||c.country===country)});arr.sort((a,b)=>sort==='name'?String(a.name).localeCompare(String(b.name),'pt-BR'):(Number(b.relevance)||0)-(Number(a.relevance)||0)||String(a.name).localeCompare(String(b.name),'pt-BR'));if($('#clubCount'))$('#clubCount').textContent=`${arr.length} clubes`;if($('#clubList'))$('#clubList').innerHTML=arr.slice(0,300).map(c=>`<article class="club-card"><b>${esc(c.short_name||c.name)}</b><span>${esc(c.name)}</span><small>${esc(c.city||'')}${c.state?` • ${esc(c.state)}`:''}<br>${esc(c.country||'')}</small><em>RELEVÂNCIA ${clamp(c.relevance||0,0,100)}</em></article>`).join('')||'<div class="empty">Nenhum clube encontrado.</div>';if($('#clubCountry')&&$('#clubCountry').options.length<=1&&clubs.length){const selected=$('#clubCountry').value;const cs=[...new Set(clubs.map(c=>c.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#clubCountry').innerHTML='<option value="">Todos os países</option>'+cs.map(c=>`<option${c===selected?' selected':''}>${esc(c)}</option>`).join('')}}
function renderMarket(){$('#marketOffers').innerHTML=S.market.length?S.market.map((o,i)=>`<article class="offer"><b>${esc(o.club)}</b><span>${esc(o.role)}</span><strong>${money(o.salary)}<small>/mês</small></strong><small>${o.years} anos</small><div><button class="btn primary" data-offer="accept" data-i="${i}">Assinar</button><button class="btn" data-offer="reject" data-i="${i}">Recusar</button></div></article>`).join(''):'<div class="empty">Nenhuma proposta aberta.</div>';$('#contractClub').textContent=S.player.club;$('#contractSalary').textContent=money(S.player.salary);$('#contractYears').textContent=S.contract.years?`${S.contract.years} anos`:'Sem contrato'}
function renderSystem(){$('#systemLevel').textContent=S.player.system;$('#copiesUsed').textContent=8-S.player.copies;$('#difficultyLabel').textContent=S.difficulty==='sss'?'SSS':'NORMAL';if($('#sysPosition'))$('#sysPosition').value=S.player.position;if($('#difficulty'))$('#difficulty').value=S.difficulty;$('#systemLog').innerHTML=S.log.slice(-10).map(x=>`<div>${esc(x)}</div>`).join('')}
function applyPage(){$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
function startForm(){const n=$('#startNationality');n.innerHTML=COUNTRIES.map(c=>`<option value="${esc(c[0])}"${c[0]==='Brasil'?' selected':''}>${c[1]} ${esc(c[0])}</option>`).join('');$('#startPosition').innerHTML=POS.map(p=>`<option>${p}</option>`).join('');$('#startDifficulty').innerHTML='<option value="normal">Normal</option><option value="sss">SSS — difícil</option>'}
function start(){const name=($('#startName').value||'Novo Craque').trim().slice(0,24)||'Novo Craque';S=fresh();S.player.name=name;S.player.nationality=$('#startNationality').value;S.player.position=$('#startPosition').value;S.difficulty=$('#startDifficulty').value;S.player.birthYear=START-S.player.age;note('DESPERTAR',`${flag(S.player.nationality)} ${S.player.nationality} • início em 1996.`);persist();$('#onboarding').classList.remove('show');render()}
function bind(){document.addEventListener('click',e=>{const n=e.target.closest('[data-page]');if(n){page=n.dataset.page;applyPage();return}const t=e.target.closest('[data-train]');if(t){train(t.dataset.train);return}if(e.target.closest('#weekBtn')){endWeek();return}if(e.target.closest('#matchBtn')){match();return}if(e.target.closest('#duelBtn')){duel();return}if(e.target.closest('#restBtn')){if(S.player.retired)return;S.player.energy=clamp(S.player.energy+22,0,100);S.player.fatigue=clamp(S.player.fatigue-18,0,100);persist();render();return}if(e.target.closest('#saveBtn')){save();return}if(e.target.closest('#newGameBtn')){S=fresh();$('#onboarding').classList.add('show');startForm();render();return}if(e.target.closest('#startBtn')){start();return}const tac=e.target.closest('[data-tactic]');if(tac){S.clubState.tactic=tac.dataset.tactic;persist();render();return}const y=e.target.closest('[data-year]');if(y){if(!$('#historyYear'))return;$('#historyYear').value=y.dataset.year;renderWorld();return}const off=e.target.closest('[data-offer]');if(off){const i=Number(off.dataset.i);if(off.dataset.offer==='accept')acceptOffer(i);else{S.market.splice(i,1);persist();render()};return}if(e.target.closest('#generateOffers')){generateOffers();return}if(e.target.closest('#ngpBtn')){if(S.career.season<5&&overall()<84)return toast('DESBLOQUEIO','New Game+ exige 5 temporadas ou overall 84.');const carry=S.talents.filter(t=>t.complete).map(t=>({...t,fragments:3}));S=fresh();S.player.name='Novo Craque+';S.player.talents=carry;S.player.system=1+carry.length;for(const t of carry)S.player.potential[t.attribute]=99;note('NEW GAME+','Uma nova linha do tempo começou com sua coleção permanente.');persist();render()}});$('#historyYear')?.addEventListener('change',renderWorld);$('#historySearch')?.addEventListener('input',renderWorld);$('#clubSearch')?.addEventListener('input',renderClubs);$('#clubCountry')?.addEventListener('change',renderClubs);$('#clubSort')?.addEventListener('change',renderClubs);$('#tactic')?.addEventListener('change',e=>{S.clubState.tactic=e.target.value;persist();render()});$('#sysPosition')?.addEventListener('change',e=>{S.player.position=e.target.value;persist();render()});$('#difficulty')?.addEventListener('change',e=>{S.difficulty=e.target.value;S.player.copies=S.difficulty==='sss'?Math.min(S.player.copies,5):Math.max(S.player.copies,8);persist();render()})}
function normalizeHistory(d){if(Array.isArray(d?.players))return{players:d.players.map((x,i)=>({id:`p${i}`,name:x[0],nationality:x[1],position:x[2],birthYear:x[3],spans:(x[4]||[]).map(s=>({from:s[0],to:s[1],club:s[2],level:s[3]==='e'?'empréstimo':'profissional'})),talent:{id:`t${i}`,name:x[5]?.[0]||'Talento',attribute:x[5]?.[1]||'mental',rarity:x[5]?.[2]||'Épico',passive:x[5]?.[3]||''}})),start:d.start||1996,end:d.end||2026};return{players:[]}}
async function loadData(){try{const r=await fetch('data/craques-mini.json',{cache:'no-store'});if(r.ok)history=normalizeHistory(await r.json())}catch{}try{const r=await fetch('data/clubs.generated.json',{cache:'no-store'});if(r.ok){const d=await r.json();clubs=d.clubs||d}}catch{}renderWorld();renderClubs()}
function boot(){load();startForm();bind();if(!localStorage.getItem(KEY))$('#onboarding').classList.add('show');render();loadData()}
window.CraqueSSS={state:()=>JSON.parse(JSON.stringify(S)),overall,newGame:()=>{$('#onboarding').classList.add('show')},save};boot();
})();
