(()=>{
'use strict';
const KEY='craque-sss-v7', START=1996, END=2026, MAX_TRAIN=3;
const ATTRS={ritmo:'Ritmo',fisico:'Físico',finalizacao:'Finalização',passe:'Passe',drible:'Drible',visao:'Visão',mental:'Mental',defesa:'Defesa',reflexo:'Reflexo'};
const PHYSICAL=new Set(['ritmo','fisico','reflexo']);
const POSITIONS=['Atacante','Ponta','Meia','Volante','Zagueiro','Goleiro'];
const COUNTRIES=[['Brasil','🇧🇷'],['Argentina','🇦🇷'],['Uruguai','🇺🇾'],['Colômbia','🇨🇴'],['Chile','🇨🇱'],['Peru','🇵🇪'],['Equador','🇪🇨'],['Paraguai','🇵🇾'],['Bolívia','🇧🇴'],['México','🇲🇽'],['Estados Unidos','🇺🇸'],['Canadá','🇨🇦'],['Costa Rica','🇨🇷'],['França','🇫🇷'],['Espanha','🇪🇸'],['Alemanha','🇩🇪'],['Itália','🇮🇹'],['Inglaterra','🏴'],['Portugal','🇵🇹'],['Países Baixos','🇳🇱'],['Bélgica','🇧🇪'],['Croácia','🇭🇷'],['Noruega','🇳🇴'],['Suécia','🇸🇪'],['Dinamarca','🇩🇰'],['Suíça','🇨🇭'],['Polônia','🇵🇱'],['Turquia','🇹🇷'],['Sérvia','🇷🇸'],['Áustria','🇦🇹'],['Marrocos','🇲🇦'],['Senegal','🇸🇳'],['Egito','🇪🇬'],['Nigéria','🇳🇬'],['Costa do Marfim','🇨🇮'],['Camarões','🇨🇲'],['Gana','🇬🇭'],['Argélia','🇩🇿'],['Tunísia','🇹🇳'],['Japão','🇯🇵'],['Coreia do Sul','🇰🇷'],['Irã','🇮🇷'],['Arábia Saudita','🇸🇦'],['Austrália','🇦🇺']];
const CUPS=new Set([1998,2002,2006,2010,2014,2018,2022,2026]);
const TRAIN={leve:{cost:16,gain:1,chance:1,fatigue:0},pesado:{cost:28,gain:3,chance:.55,fatigue:10},espartano:{cost:46,gain:6,chance:.28,fatigue:24}};
const FOCUS={Atacante:['finalizacao','ritmo','mental'],Ponta:['drible','ritmo','passe'],Meia:['passe','visao','mental'],Volante:['defesa','fisico','passe'],Zagueiro:['defesa','fisico','mental'],Goleiro:['reflexo','fisico','mental']};
let history={players:[]}, clubs=[], page='carreira', selectedYear=1996, toastTimer=0;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const chance=p=>Math.random()<p;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Math.max(0,Math.round(v||0)));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const deep=x=>JSON.parse(JSON.stringify(x));
const flag=n=>COUNTRIES.find(c=>c[0]===n)?.[1]||'🌎';
function fresh(){const attrs={ritmo:24,fisico:23,finalizacao:22,passe:25,drible:26,visao:24,mental:21,defesa:21,reflexo:20};return{version:7,worldYear:START,player:{name:'Novo Craque',nationality:'Brasil',age:15,birthYear:1981,position:'Ponta',category:'Sub-15',club:'Academia Local',salary:0,energy:100,fatigue:0,morale:72,form:68,loyalty:55,injuredMatches:0,temporaryPhysicalPenalty:0,temporaryPenaltyMatches:0,attrs,potential:Object.fromEntries(Object.keys(attrs).map(k=>[k,80])),copies:8,systemLevel:1,copyUsed:0,retired:false},career:{season:1,week:1,phase:'Pré-temporada',trainingsUsed:0,matches:0,wins:0,draws:0,losses:0,goals:0,assists:0,titles:0,value:1000,totalSeasons:0,history:[]},clubState:{tactic:'equilibrado',chemistry:55,managerTrust:45},contract:{yearsLeft:0,agent:'Conservador',clause:0},market:{offers:[]},national:{calledUp:false,caps:0,goals:0,assists:0,titles:0,role:'Fora da convocação'},worldCup:{stage:'Não classificado',champion:null},talents:[],notifications:[{title:'DESPERTAR',body:'1996. O Sistema encontrou você.'}],log:['[SISTEMA] Linha do tempo sincronizada em 1996.']};}
let state=fresh();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{return false}}
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(!raw||raw.version!==7)return;const f=fresh();state={...f,...raw,player:{...f.player,...raw.player,attrs:{...f.player.attrs,...raw.player?.attrs},potential:{...f.player.potential,...raw.player?.potential}},career:{...f.career,...raw.career},clubState:{...f.clubState,...raw.clubState},contract:{...f.contract,...raw.contract},market:{...f.market,...raw.market},national:{...f.national,...raw.national},worldCup:{...f.worldCup,...raw.worldCup}}}catch{state=fresh()}}
function notify(t,m){const e=q('#toast');if(!e)return;e.innerHTML=`<b>${esc(t)}</b><span>${esc(m)}</span>`;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3200)}
function event(title,body){state.notifications.unshift({id:uid('n'),title,body,year:state.worldYear});state.notifications=state.notifications.slice(0,60);notify(title,body)}
function log(text,type='SISTEMA'){state.log.push(`[${type}] ${text}`);state.log=state.log.slice(-60)}
function effective(k){const v=clamp(state.player.attrs[k],1,99);return PHYSICAL.has(k)?clamp(v-state.player.temporaryPhysicalPenalty,1,99):v}
function overall(){const keys=Object.keys(ATTRS);const base=keys.reduce((s,k)=>s+effective(k),0)/keys.length;const pos=state.player.position==='Goleiro'?((effective('reflexo')-40)*.22):((effective('finalizacao')+effective('drible')-80)*.03);return Math.round(clamp(base+pos+state.talents.filter(t=>t.complete).length*1.5,1,99))}
function categoryFor(age,ovr){if(age>=19&&ovr>=84)return'Seleção Principal';if(age>=18&&ovr>=72)return'Europa';if(age>=17&&ovr>=55)return'Estreante Profissional';if(age>=16&&ovr>=40)return'Sub-17';return'Sub-15'}
function activeStars(year){return history.players.filter(p=>p.spans.some(s=>s.level==='profissional'&&year>=s.from&&year<=s.to&&year>=p.birthYear+15))}
function clubAt(p,y){return p.spans.filter(s=>y>=s.from&&y<=s.to).map(s=>`${s.club}${s.level==='empréstimo'?' (empréstimo)':''}`).join(' / ')}
function duelTarget(){const done=new Set(state.talents.filter(t=>t.complete).map(t=>t.id));const candidates=activeStars(state.worldYear).filter(p=>!done.has(p.talent.id));const p=candidates[0];if(!p)return null;return{owner:p,talent:p.talent,ovr:clamp(35+Math.round((state.worldYear-p.birthYear)*1.3),25,96)}}
function train(type){if(state.player.retired)return notify('APOSENTADO','A carreira terminou.');if(state.player.injuredMatches)return notify('LESIONADO',`Fora por ${state.player.injuredMatches} partidas.`);if(state.career.trainingsUsed>=MAX_TRAIN)return notify('LIMITE SEMANAL','Você já fez 3 sessões nesta semana.');const spec=TRAIN[type];if(!spec||state.player.energy<spec.cost)return notify('ENERGIA','Você precisa administrar sua recuperação.');state.career.trainingsUsed++;state.player.energy-=spec.cost;const pool=FOCUS[state.player.position]||FOCUS.Ponta;const attr=pool[rand(0,pool.length-1)];if(chance(spec.chance)){const gain=Math.min(spec.gain,Math.max(0,state.player.potential[attr]-state.player.attrs[attr]));state.player.attrs[attr]+=gain;state.player.form=clamp(state.player.form+(gain?2:0),0,100);log(`${spec.label}: +${gain} ${ATTRS[attr]}.`,'TREINO')}else{state.player.morale=clamp(state.player.morale-(type==='espartano'?5:2),0,100);log(`${spec.label}: sessão falhou.`,'FALHA')}state.player.fatigue=clamp(state.player.fatigue+spec.fatigue,0,100);if(type==='pesado'&&chance(.15)){state.player.temporaryPhysicalPenalty=rand(2,4);state.player.temporaryPenaltyMatches=1;event('FADIGA FÍSICA',`- ${state.player.temporaryPhysicalPenalty} nos atributos físicos por 1 partida.`)}if(type==='espartano'&&chance(.25)){state.player.injuredMatches=rand(3,10);state.player.energy=8;event('LESÃO GRAVE',`Você ficará fora por ${state.player.injuredMatches} partidas.`)}save();render()}
function duel(){if(state.player.retired)return notify('APOSENTADO','Sem novos duelos.');if(state.player.copies<1)return notify('SEM CÓPIAS','Os Pontos de Cópia acabaram.');if(state.player.injuredMatches||state.player.energy<22)return notify('INDISPONÍVEL','Você precisa estar apto e com energia.');const t=duelTarget();if(!t)return notify('SEM ALVO','Nenhum craque ativo disponível em '+state.worldYear+'.');const c=clamp(Math.round(46+(overall()-t.ovr)*1.45+(state.player.form-50)*.12-(state.difficulty==='sss'?8:0)),8,92);state.player.copies--;state.player.copyUsed++;state.player.energy-=13;if(chance(c/100)){let own=state.talents.find(x=>x.id===t.talent.id);if(!own){own={...deep(t.talent),fragments:0,complete:false};state.talents.push(own)}own.fragments=clamp((own.fragments||0)+1,0,3);if(own.fragments===3&&!own.complete){own.complete=true;state.player.potential[t.talent.attribute]=99;state.player.systemLevel++;event('HABILIDADE ADQUIRIDA',`${own.name} completa. Origem: ${t.owner.name}.`)}else event('FRAGMENTO ROUBADO',`${own.name}: ${own.fragments}/3 • ${t.owner.name} • ${clubAt(t.owner,state.worldYear)}`);state.player.form=clamp(state.player.form+3,0,100)}else{state.player.morale=clamp(state.player.morale-3,0,100);event('DUELO PERDIDO',`Chance ${c}%. ${t.owner.name} protegeu seu talento.`)}save();render()}
function match(){if(state.player.retired)return notify('APOSENTADO','Não há partidas.');if(state.player.injuredMatches)return notify('LESIONADO',`Fora por ${state.player.injuredMatches} partidas.`);if(state.player.energy<18)return notify('SEM ENERGIA','Recupere-se antes do jogo.');const tactic={seguro:-5,equilibrado:0,protagonista:6}[state.clubState.tactic]||0;const opp=clamp(overall()+rand(-8,10),20,96),perf=overall()-opp+tactic+(state.player.form-50)*.12+(state.clubState.chemistry-50)*.06+rand(-9,9),out=perf>=7?'win':perf<=-7?'loss':'draw';const goals=state.player.position==='Goleiro'?0:(out==='win'?rand(0,2):chance(.22)?1:0),assists=chance(.24)&&goals<2?1:0;state.career.matches++;if(out==='win')state.career.wins++;else if(out==='draw')state.career.draws++;else state.career.losses++;state.career.goals+=goals;state.career.assists+=assists;const rating=clamp(5.1+perf*.08+goals*1.1+assists*.6,3,10);state.player.energy=clamp(state.player.energy-(state.clubState.tactic==='seguro'?5:state.clubState.tactic==='protagonista'?17:10),0,100);state.player.fatigue=clamp(state.player.fatigue+8,0,100);state.player.form=clamp(state.player.form+(rating>=7?4:rating<5.5?-3:1),0,100);state.player.morale=clamp(state.player.morale+(out==='win'?4:out==='loss'?-4:1),0,100);state.career.value=Math.round(state.career.value*(1+(rating-6)*.025)+goals*5000+assists*2200);if(chance(.04+state.player.fatigue/1400)){state.player.injuredMatches=rand(1,2);event('LESÃO NA PARTIDA',`Fora por ${state.player.injuredMatches} partidas.`)}event('PARTIDA',`${out==='win'?'Vitória':out==='draw'?'Empate':'Derrota'} • nota ${rating.toFixed(1)} • ${goals}G/${assists}A`);tickPenalty();save();render()}
function tickPenalty(){if(state.player.temporaryPenaltyMatches){state.player.temporaryPenaltyMatches--;if(!state.player.temporaryPenaltyMatches)state.player.temporaryPhysicalPenalty=0}}
function nationalCheck(){if(state.player.age>=18&&overall()>=65&&state.player.form>=52){state.national.calledUp=true;state.national.caps++;state.national.role='Convocado';event('SELEÇÃO NACIONAL',`${flag(state.player.nationality)} ${state.player.nationality}: você foi convocado.`)}}
function worldCupCheck(){if(!CUPS.has(state.worldYear))return;const ok=state.player.age>=18&&overall()>=70&&state.player.form>=55;state.national.calledUp=ok;state.national.role=ok?'Convocado para a Copa':'Fora da Copa';state.worldCup.stage=ok?'Fase de grupos':'Não classificado';if(ok){state.national.caps++;event('COPA DO MUNDO',`${flag(state.player.nationality)} Copa de ${state.worldYear}: você está convocado.`)}else event('COPA DO MUNDO','Você ainda não atingiu os critérios desta edição.')}
function generateOffers(){if(state.player.retired)return;const o=overall();const pools=o>=85?['Real Madrid','Barcelona','Manchester City']:o>=72?['Bayern München','Paris Saint-Germain','Flamengo']:o>=50?['Palmeiras','Sport','Bahia']:['ABC Futebol Clube','América-RN','Potiguar de Mossoró'];state.market.offers=pools.slice(0,3).map((club,i)=>({id:uid('offer'),club,salary:Math.round(Math.max(1800,o*(1100+i*240))),years:2+(i%2),role:i===0?'Disputa de titular':i===1?'Rotação':'Projeto'}));event('MERCADO',`${state.market.offers.length} propostas chegaram.`);save();render()}
function acceptOffer(id){const o=state.market.offers.find(x=>x.id===id);if(!o)return;state.player.club=o.club;state.player.salary=o.salary;state.contract.yearsLeft=o.years;state.contract.clause=Math.round(o.salary*36);state.player.loyalty=clamp(state.player.loyalty-10,0,100);state.market.offers=[];event('TRANSFERÊNCIA',`Você assinou com ${o.club}. ${money(o.salary)}/mês.`);save();render()}
function rejectOffer(id){state.market.offers=state.market.offers.filter(x=>x.id!==id);save();render()}
function endWeek(){if(state.player.retired)return; if(state.career.week>=10){endSeason();return}state.career.week++;state.career.trainingsUsed=0;state.career.phase=state.career.week<=2?'Pré-temporada':'Rodadas';state.player.energy=clamp(state.player.energy+38-Math.round(state.player.fatigue*.35),0,100);state.player.fatigue=clamp(state.player.fatigue-22,0,100);state.player.form=clamp(state.player.form+1,0,100);if(state.player.injuredMatches)state.player.injuredMatches--;tickPenalty();if(state.career.week===7&&[1996,2000,2004,2008,2012,2016,2020,2024].includes(state.worldYear))nationalCheck();if(state.career.week===8)worldCupCheck();save();render()}
function endSeason(){const y=state.worldYear,o=overall();state.career.history.unshift({year:y,age:state.player.age,overall:o,club:state.player.club,goals:state.career.goals,wins:state.career.wins});state.career.totalSeasons++;state.worldYear++;state.player.age++;state.player.birthYear=state.worldYear-state.player.age;state.career.season++;state.career.week=1;state.career.trainingsUsed=0;state.player.energy=100;state.player.fatigue=0;state.player.injuredMatches=0;state.player.temporaryPhysicalPenalty=0;state.player.temporaryPenaltyMatches=0;state.player.form=clamp(state.player.form+3,0,100);if(state.contract.yearsLeft)state.contract.yearsLeft--;if(state.player.age>=31)for(const k of PHYSICAL)state.player.attrs[k]=clamp(state.player.attrs[k]-rand(2,4),1,99);const old=state.player.category;state.player.category=categoryFor(state.player.age,overall());if(old!==state.player.category)event('PROMOÇÃO',`Você avançou para ${state.player.category}.`);if(state.career.wins>=6&&state.career.goals>=8){state.career.titles++;event('🏆 TÍTULO',`Temporada ${y} terminou com taça.`)}if(state.worldYear>END){state.player.retired=true;event('APOSENTADORIA','A linha do tempo chegou ao fim da carreira.')}else generateOffers();save();render()}
function startCareer(){const name=(q('#startName')?.value||'Novo Craque').trim().slice(0,28)||'Novo Craque';const nationality=q('#startNationality')?.value||'Brasil';const position=q('#startPosition')?.value||'Ponta';const difficulty=q('#startDifficulty')?.value==='sss'?'sss':'normal';state=fresh();state.player.name=name;state.player.nationality=COUNTRIES.some(c=>c[0]===nationality)?nationality:'Brasil';state.player.position=POSITIONS.includes(position)?position:'Ponta';state.difficulty=difficulty;if(difficulty==='sss')state.player.copies=5;save();q('#onboarding')?.classList.remove('show');render()}
function newGame(){state=fresh();save();q('#onboarding')?.classList.add('show');render()}
function newGamePlus(){if(state.career.totalSeasons<5&&overall()<84)return notify('DESBLOQUEIO','New Game+ exige 5 temporadas ou overall 84.');const carry=state.talents.filter(t=>t.complete).map(deep);const name=state.player.name;state=fresh();state.player.name=name+'+';state.player.nationality=state.player.nationality;state.talents=carry;state.player.systemLevel=1+carry.length;for(const t of carry)if(t.attribute)state.player.potential[t.attribute]=99;event('NEW GAME+','Sua coleção de talentos foi carregada para uma nova linha do tempo.');save();render()}
function renderTop(){q('#copyTop').textContent=state.player.copies;q('#year').textContent=state.worldYear;q('#week').textContent=state.career.week;q('#season').textContent=String(state.career.season).padStart(2,'0');q('#topFlag').textContent=flag(state.player.nationality);q('#topNat').textContent=state.player.nationality;q('#retiredPill')?.classList.toggle('show',state.player.retired)}
function renderCareer(){const o=overall();const set=(id,v)=>{const e=q(id);if(e)e.textContent=v};set('#playerName',state.player.name);set('#name',state.player.name);set('#playerNat',`${flag(state.player.nationality)} ${state.player.nationality}`);set('#ovr',o);set('#age',state.player.age);set('#position',state.player.position);set('#category',state.player.category);set('#playerClub',state.player.club);set('#energy',`${state.player.energy}%`);set('#fatigue',`${state.player.fatigue}%`);set('#morale',`${state.player.morale}%`);set('#form',`${state.player.form}%`);set('#salary',money(state.player.salary));set('#marketValue',money(state.career.value));set('#loyalty',`${state.player.loyalty}%`);set('#starterChance',`${Math.round(clamp(48+(o-45)*.5,0,100))}%`);set('#managerTrust',`${state.clubState.managerTrust}%`);set('#trophies',state.career.titles);set('#careerContractClub',state.player.club);set('#careerContractYears',state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato');set('#agentLabel',state.contract.agent);set('#contractClause',money(state.contract.clause));set('#matchStatus',state.player.injuredMatches?`Fora ${state.player.injuredMatches} partidas.`:'Apto');const d=duelTarget(),c=d?clamp(Math.round(46+(o-d.ovr)*1.45+(state.player.form-50)*.12-(state.difficulty==='sss'?8:0)),8,92):0;set('#nextOpponent',d?.owner?.name||'Nenhum craque ativo');set('#opponentOvr',d?.ovr??'—');set('#targetTalent',d?.talent?.name||'—');set('#duelChance',d?`${c}%`:'—');const bar=q('#duelBar');if(bar)bar.style.width=d?`${c}%`:'0%';if(q('#tactic'))q('#tactic').value=state.clubState.tactic;if(q('#clubState'))q('#clubState').textContent=state.clubState.tactic==='protagonista'?'Protagonista':state.clubState.tactic==='seguro'?'Seguro':'Equilibrado';set('#record',`${state.career.wins}V ${state.career.draws}E ${state.career.losses}D`);if(q('#historyLog'))q('#historyLog').innerHTML=state.notifications.slice(0,5).map(n=>`<div class="notice-line"><b>${esc(n.title)}</b><span>${esc(n.body)}</span></div>`).join('')||'<div class="empty">O Sistema ainda está silencioso.</div>';renderAttrs();renderTalents()}
function renderAttrs(){const html=Object.entries(ATTRS).map(([k,v])=>`<div class="attr"><div><span>${v}</span><small>teto ${state.player.potential[k]}${PHYSICAL.has(k)&&state.player.temporaryPhysicalPenalty?` • -${state.player.temporaryPhysicalPenalty} temp.`:''}</small></div><div class="bar"><i style="width:${effective(k)}%"></i></div><b>${effective(k)}</b></div>`).join('');if(q('#attrs'))q('#attrs').innerHTML=html;if(q('#attrs2'))q('#attrs2').innerHTML=html}
function renderTalents(){if(!q('#talents'))return;q('#talents').innerHTML=state.talents.length?state.talents.map(t=>`<article class="talent ${t.complete?'complete':''}"><div class="gem">✦</div><div><b>${esc(t.name)}</b><small>${t.fragments||0}/3 • ${t.complete?'PASSIVA PERMANENTE':esc(t.origin||'Craque da época')}</small></div><strong>${t.complete?'SSS':`${t.fragments||0}/3`}</strong></article>`).join(''):'<div class="empty">Nenhum talento coletado.</div>'}
function renderTraining(){const e=q('#trainRemain');if(e)e.textContent=`${MAX_TRAININGS-state.career.trainingsUsed}/${MAX_TRAIN} sessões`;qa('[data-train]').forEach(b=>b.disabled=state.player.retired||!!state.player.injuredMatches||state.career.trainingsUsed>=MAX_TRAIN)}
function renderSelection(){const set=(id,v)=>{const e=q(id);if(e)e.textContent=v};set('#nationalFlag',flag(state.player.nationality));set('#nationalName',`Seleção ${state.player.nationality}`);set('#nationalName2',`Seleção ${state.player.nationality}`);set('#nationalRole',state.national.role);set('#nationalCaps',state.national.caps);set('#nationalOvr',Math.round(clamp(50+overall()/2,50,99)));set('#selectionStatus',state.player.age>=18&&overall()>=65?'Você está no radar da seleção.':'Ainda não atende aos requisitos.');set('#nextCup',[...CUPS].find(y=>y>=state.worldYear)||2030)}
function renderWorld(){const inp=q('#historyYear');const y=clamp(Number(inp?.value||selectedYear),START,END);selectedYear=y;const term=(q('#historySearch')?.value||'').toLowerCase();const arr=activeStars(y).filter(p=>!term||p.name.toLowerCase().includes(term)||p.nationality.toLowerCase().includes(term)||clubAt(p,y).toLowerCase().includes(term));if(q('#historyYearLabel'))q('#historyYearLabel').textContent=y;if(q('#historyCount'))q('#historyCount').textContent=`${arr.length} craques encontrados`;if(q('#historyPlayers'))q('#historyPlayers').innerHTML=arr.map(p=>`<article class="history-card"><div class="history-avatar">${flag(p.nationality)}</div><div><b>${esc(p.name)}</b><small>${esc(p.position)} • ${esc(p.nationality)} • nasceu em ${p.birthYear}</small><strong>${esc(clubAt(p,y)||'Sem clube profissional')}</strong><em>${esc(p.talent?.name||'Talento')}</em></div></article>`).join('')||'<div class="empty">Nenhum craque profissional encontrado neste ano.</div>';if(q('#historyYears'))q('#historyYears').innerHTML=[1996,2000,2004,2008,2012,2016,2020,2024].map(n=>`<button class="year-chip ${n===y?'active':''}" data-year="${n}">${n}</button>`).join('')}
function renderMarket(){if(q('#marketOffers'))q('#marketOffers').innerHTML=state.market.offers.length?state.market.offers.map(o=>`<article class="offer"><b>${esc(o.club)}</b><span>${esc(o.role)}</span><strong>${money(o.salary)}<small>/mês</small></strong><small>${o.years} anos</small><div><button class="btn primary" data-offer="accept" data-id="${esc(o.id)}">Assinar</button><button class="btn" data-offer="reject" data-id="${esc(o.id)}">Recusar</button></div></article>`).join(''):'<div class="empty">Nenhuma proposta aberta.</div>';const set=(id,v)=>{const e=q(id);if(e)e.textContent=v};set('#contractClub',state.player.club);set('#contractSalary',money(state.player.salary));set('#contractYears',state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato')}
function renderClubs(){const term=(q('#clubSearch')?.value||'').toLowerCase(),country=q('#clubCountry')?.value||'',sort=q('#clubSort')?.value||'rel';let arr=clubs.filter(c=>{const text=[c.name,c.city,c.state,c.country,c.short_name,...(c.aliases||[])].join(' ').toLowerCase();return(!term||text.includes(term))&&(!country||c.country===country)});arr.sort((a,b)=>sort==='name'?String(a.name).localeCompare(String(b.name),'pt-BR'):(Number(b.relevance)||0)-(Number(a.relevance)||0)||String(a.name).localeCompare(String(b.name),'pt-BR'));if(q('#clubCount'))q('#clubCount').textContent=`${arr.length} clubes`;if(q('#clubList'))q('#clubList').innerHTML=arr.slice(0,300).map(c=>`<article class="club-card"><b>${esc(c.short_name||c.name)}</b><span>${esc(c.name)}</span><small>${esc(c.city||'')}${c.state?` • ${esc(c.state)}`:''}<br>${esc(c.country||'')}</small><em>RELEVÂNCIA ${clamp(c.relevance||0,0,100)}</em></article>`).join('')||'<div class="empty">Nenhum clube encontrado.</div>';if(q('#clubCountry')&&q('#clubCountry').options.length<=1&&clubs.length){const cs=[...new Set(clubs.map(c=>c.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));q('#clubCountry').innerHTML='<option value="">Todos os países</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}}
function renderSystem(){const set=(id,v)=>{const e=q(id);if(e)e.textContent=v};set('#systemLevel',state.player.systemLevel);set('#copiesUsed',state.player.copyUsed);set('#difficultyLabel',state.difficulty.toUpperCase());if(q('#sysPosition'))q('#sysPosition').value=state.player.position;if(q('#difficulty'))q('#difficulty').value=state.difficulty;if(q('#systemLog'))q('#systemLog').innerHTML=state.log.slice(-9).map(x=>`<div>${esc(x)}</div>`).join('');if(q('#achievements'))q('#achievements').innerHTML=state.career.history.slice(0,8).map(h=>`<div class="achievement"><b>${h.year} • OVR ${h.overall}</b><span>${esc(h.club)} • ${h.goals} gols</span></div>`).join('')||'<div class="empty">As conquistas aparecerão durante a carreira.</div>';if(q('#ngpBtn'))q('#ngpBtn').disabled=state.career.totalSeasons<5&&overall()<84}
function renderStartForm(){const s=q('#startNationality');if(s&&!s.options.length)s.innerHTML=COUNTRIES.map(c=>`<option value="${esc(c[0])}">${c[1]} ${esc(c[0])}</option>`).join('');const p=q('#startPosition');if(p&&!p.options.length)p.innerHTML=POSITIONS.map(x=>`<option>${x}</option>`).join('')}
function render(){renderTop();renderCareer();renderTraining();renderSelection();renderWorld();renderMarket();renderClubs();renderSystem();applyPage()}
function applyPage(){qa('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));qa('.page').forEach(s=>s.classList.toggle('active',s.id===`page-${page}`))}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;applyPage();return}const tr=e.target.closest('[data-train]');if(tr){train(tr.dataset.train);return}if(e.target.closest('#weekBtn')){endWeek();return}if(e.target.closest('#duelBtn')){duel();return}if(e.target.closest('[data-action="match"]')){const a=e.target.closest('[data-action="match"]')?.dataset.approach;if(a)state.clubState.tactic=a;match();return}if(e.target.closest('#newGameBtn')){newGame();return}if(e.target.closest('#restBtn')){state.player.energy=clamp(state.player.energy+22,0,100);state.player.fatigue=clamp(state.player.fatigue-18,0,100);save();render();return}if(e.target.closest('#saveBtn')){save();notify('SALVO','Carreira gravada neste dispositivo.');return}const yr=e.target.closest('[data-year]');if(yr){if(q('#historyYear'))q('#historyYear').value=yr.dataset.year;selectedYear=Number(yr.dataset.year);renderWorld();return}const offer=e.target.closest('[data-offer]');if(offer){offer.dataset.offer==='accept'?acceptOffer(offer.dataset.id):rejectOffer(offer.dataset.id);return}if(e.target.closest('#generateOffers')){generateOffers();return}if(e.target.closest('#ngpBtn')){newGamePlus();return}if(e.target.closest('#startBtn')){startCareer();return}});if(q('#historyYear'))q('#historyYear').addEventListener('change',renderWorld);if(q('#historySearch'))q('#historySearch').addEventListener('input',renderWorld);if(q('#clubSearch'))q('#clubSearch').addEventListener('input',renderClubs);if(q('#clubCountry'))q('#clubCountry').addEventListener('change',renderClubs);if(q('#clubSort'))q('#clubSort').addEventListener('change',renderClubs);if(q('#tactic'))q('#tactic').addEventListener('change',e=>{state.clubState.tactic=e.target.value;save();render()});if(q('#sysPosition'))q('#sysPosition').addEventListener('change',e=>{if(POSITIONS.includes(e.target.value)){state.player.position=e.target.value;save();render()}});if(q('#difficulty'))q('#difficulty').addEventListener('change',e=>{state.difficulty=e.target.value==='sss'?'sss':'normal';state.player.copies=state.difficulty==='sss'?Math.min(state.player.copies,5):Math.max(state.player.copies,8);save();render()})}
async function loadData(){try{const r=await fetch('data/craques-mini.json',{cache:'no-store'});if(r.ok)history=await r.json()}catch{}try{const r=await fetch('data/clubs.generated.json',{cache:'no-store'});if(r.ok){const d=await r.json();clubs=d.clubs||d}}catch{}render()}
function boot(){load();renderStartForm();bind();render();if(!localStorage.getItem(KEY)){q('#onboarding')?.classList.add('show')}loadData()}
window.CraqueSSS={getState:()=>deep(state),newGame,save,overall};boot();
})();
