(()=>{
  'use strict';
  const SAVE_KEY='craque-sss-v6', START_YEAR=1996, END_YEAR=2026, MAX_TRAININGS=3;
  const ATTRS={ritmo:'Ritmo',fisico:'Físico',finalizacao:'Finalização',passe:'Passe',drible:'Drible',visao:'Visão',mental:'Mental',defesa:'Defesa',reflexo:'Reflexo'};
  const PHYSICAL=new Set(['ritmo','fisico','reflexo']);
  const POSITIONS=['Atacante','Ponta','Meia','Volante','Zagueiro','Goleiro'];
  const COUNTRIES=[
    ['Brasil','🇧🇷'],['Argentina','🇦🇷'],['Uruguai','🇺🇾'],['Colômbia','🇨🇴'],['Chile','🇨🇱'],['Peru','🇵🇪'],['Equador','🇪🇨'],['Paraguai','🇵🇾'],['Bolívia','🇧🇴'],
    ['México','🇲🇽'],['Estados Unidos','🇺🇸'],['Canadá','🇨🇦'],['Costa Rica','🇨🇷'],['França','🇫🇷'],['Espanha','🇪🇸'],['Alemanha','🇩🇪'],['Itália','🇮🇹'],['Inglaterra','🏴'],['Portugal','🇵🇹'],
    ['Países Baixos','🇳🇱'],['Bélgica','🇧🇪'],['Croácia','🇭🇷'],['Noruega','🇳🇴'],['Suécia','🇸🇪'],['Dinamarca','🇩🇰'],['Suíça','🇨🇭'],['Polônia','🇵🇱'],['Turquia','🇹🇷'],['Sérvia','🇷🇸'],['Áustria','🇦🇹'],
    ['Marrocos','🇲🇦'],['Senegal','🇸🇳'],['Egito','🇪🇬'],['Nigéria','🇳🇬'],['Costa do Marfim','🇨🇮'],['Camarões','🇨🇲'],['Gana','🇬🇭'],['Argélia','🇩🇿'],['Tunísia','🇹🇳'],['Japão','🇯🇵'],['Coreia do Sul','🇰🇷'],['Irã','🇮🇷'],['Arábia Saudita','🇸🇦'],['Austrália','🇦🇺']
  ];
  const CUPS=[1998,2002,2006,2010,2014,2018,2022,2026];
  const TRAIN={leve:{cost:16,chance:1,gain:1,fatigue:0},pesado:{cost:28,chance:.5,gain:3,fatigue:10},espartano:{cost:46,chance:.2,gain:6,fatigue:24}};
  const POSITION_FOCUS={Atacante:['finalizacao','ritmo','mental'],Ponta:['drible','ritmo','passe'],Meia:['passe','visao','mental'],Volante:['defesa','fisico','passe'],Zagueiro:['defesa','fisico','mental'],Goleiro:['reflexo','fisico','mental']};
  let historyData={players:[]}, clubs=[], page='carreira', toastTimer=0;
  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
  const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
  const chance=p=>Math.random()<p;
  const deep=x=>JSON.parse(JSON.stringify(x));
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Math.max(0,Math.round(v||0)));
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  const flagFor=n=>COUNTRIES.find(c=>c[0]===n)?.[1]||'🌎';
  function fresh(){const attrs={ritmo:24,fisico:23,finalizacao:22,passe:25,drible:26,visao:24,mental:21,defesa:21,reflexo:20};return{version:6,worldYear:1996,difficulty:'normal',player:{name:'Novo Craque',nationality:'Brasil',age:15,birthYear:1981,position:'Ponta',category:'Sub-15',club:'Academia Local',salary:0,energy:100,fatigue:0,morale:72,form:68,loyalty:55,injuredMatches:0,temporaryPhysicalPenalty:0,temporaryPenaltyMatches:0,attrs,potential:Object.fromEntries(Object.keys(attrs).map(k=>[k,80])),copies:8,systemLevel:1,copyUsed:0,retired:false},career:{season:1,week:1,phase:'Pré-temporada',trainingsUsed:0,matches:0,wins:0,draws:0,losses:0,goals:0,assists:0,titles:0,value:1000,totalSeasons:0,history:[]},clubState:{tactic:'equilibrado',chemistry:55,managerTrust:45},contract:{yearsLeft:0,agent:'Conservador',clause:0},market:{offers:[]},national:{calledUp:false,caps:0,goals:0,assists:0,titles:0,role:'Fora da convocação'},worldCup:{stage:'Não classificado',champion:null},talents:[],notifications:[{title:'DESPERTAR',body:'1996. O Sistema encontrou você. A linha do tempo foi sincronizada.'}],log:['[SISTEMA] O mundo ainda não sabe seu nome.']};}
  let state=fresh();
  function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));return true}catch(e){return false}}
  function load(){try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(!raw||raw.version!==6)return;const f=fresh();state={...f,...raw,player:{...f.player,...raw.player,attrs:{...f.player.attrs,...(raw.player?.attrs||{})},potential:{...f.player.potential,...(raw.player?.potential||{})}},career:{...f.career,...raw.career},clubState:{...f.clubState,...raw.clubState},contract:{...f.contract,...raw.contract},market:{...f.market,...raw.market},national:{...f.national,...raw.national},worldCup:{...f.worldCup,...raw.worldCup}};state.player.age=clamp(state.player.age,15,55);state.worldYear=clamp(state.worldYear,START_YEAR,END_YEAR);state.player.energy=clamp(state.player.energy,0,100);state.player.fatigue=clamp(state.player.fatigue,0,100);state.player.morale=clamp(state.player.morale,0,100);state.player.form=clamp(state.player.form,0,100);state.player.loyalty=clamp(state.player.loyalty,0,100);state.player.copies=clamp(state.player.copies,0,999);state.player.injuredMatches=clamp(state.player.injuredMatches||0,0,10);state.player.temporaryPhysicalPenalty=clamp(state.player.temporaryPhysicalPenalty||0,0,8);state.player.temporaryPenaltyMatches=clamp(state.player.temporaryPenaltyMatches||0,0,4);state.career.trainingsUsed=clamp(state.career.trainingsUsed,0,MAX_TRAININGS);state.talents=Array.isArray(state.talents)?state.talents:[];state.market.offers=Array.isArray(state.market.offers)?state.market.offers:[];state.notifications=Array.isArray(state.notifications)?state.notifications.slice(0,60):[];state.log=Array.isArray(state.log)?state.log.slice(-60):[]}catch(e){state=fresh()}}
  function notify(t,m){const el=q('#toast');if(!el)return;el.innerHTML=`<b>${esc(t)}</b><span>${esc(m)}</span>`;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
  function event(title,body){state.notifications.unshift({id:uid('n'),title,body,year:state.worldYear});state.notifications=state.notifications.slice(0,60);notify(title,body)}
  function log(text,type='SISTEMA'){state.log.push(`[${type}] ${text}`);state.log=state.log.slice(-60)}
  function effective(k){const v=clamp(state.player.attrs[k],1,99);return PHYSICAL.has(k)?clamp(v-state.player.temporaryPhysicalPenalty,1,99):v}
  function overall(){const base=Object.keys(ATTRS).reduce((sum,k)=>sum+effective(k),0)/Object.keys(ATTRS).length;const pos=state.player.position==='Goleiro'?((effective('reflexo')-40)*.2):((effective('finalizacao')+effective('drible')-80)*.03);return Math.round(clamp(base+pos+state.talents.filter(t=>t.complete).length*1.5,1,99))}
  function categoryFor(age,ovr){if(age>=19&&ovr>=84)return'Seleção Principal';if(age>=18&&ovr>=72)return'Europa';if(age>=17&&ovr>=55)return'Estreante Profissional';if(age>=16&&ovr>=40)return'Sub-17';return'Sub-15'}
  function activeStars(year){return historyData.players.filter(p=>p.spans.some(s=>s.level==='profissional'&&year>=s.from&&year<=s.to&&year>=p.birthYear+15))}
  function clubAt(p,y){return p.spans.filter(s=>y>=s.from&&y<=s.to).map(s=>`${s.club}${s.level==='empréstimo'?' (empréstimo)':''}`).join(' / ')}
  function duelTarget(){const used=new Set(state.talents.filter(t=>t.complete).map(t=>t.id));const stars=activeStars(state.worldYear).filter(p=>!used.has(p.talent.id));const p=stars[0];if(!p)return null;const o=clamp(35+Math.round((state.worldYear-p.birthYear)*1.3),25,96);return{owner:p,talent:p.talent,ovr:o}}
  function train(type){if(state.player.retired)return notify('APOSENTADO','Sua carreira terminou.');if(state.player.injuredMatches)return notify('LESIONADO',`Você está fora por ${state.player.injuredMatches} partida(s).`);if(state.career.trainingsUsed>=MAX_TRAININGS)return notify('LIMITE SEMANAL','Você já fez 3 sessões nesta semana.');const spec=TRAIN[type];if(state.player.energy<spec.cost)return notify('ENERGIA BAIXA','Recupere energia antes de treinar.');state.career.trainingsUsed++;state.player.energy-=spec.cost;const pool=POSITION_FOCUS[state.player.position]||POSITION_FOCUS.Ponta;const attr=pool[rand(0,pool.length-1)];const before=overall();if(chance(spec.chance)){const gain=Math.min(spec.gain,Math.max(0,state.player.potential[attr]-state.player.attrs[attr]));state.player.attrs[attr]=clamp(state.player.attrs[attr]+gain,1,99);state.player.form=clamp(state.player.form+(gain?2:0),0,100);log(`${spec.label}: +${gain} ${ATTRS[attr]}.`,'TREINO')}else{state.player.morale=clamp(state.player.morale-(type==='espartano'?5:2),0,100);log(`${spec.label}: sessão falhou.`,'FALHA')}state.player.fatigue=clamp(state.player.fatigue+spec.fatigue,0,100);if(type==='pesado'&&chance(.15)){state.player.temporaryPhysicalPenalty=rand(2,4);state.player.temporaryPenaltyMatches=1;event('FADIGA FÍSICA',`- ${state.player.temporaryPhysicalPenalty} temporário nos atributos físicos.`)}if(type==='espartano'&&chance(.25)){state.player.injuredMatches=rand(3,10);state.player.energy=8;event('LESÃO GRAVE',`Você ficará fora por ${state.player.injuredMatches} partidas.`)}if(overall()-before>=5)event('REAÇÃO DO MUNDO',`Seu overall saltou de ${before} para ${overall()}. A imprensa começa a desconfiar da evolução.`);save();render()}
  function duel(){if(state.player.retired)return notify('APOSENTADO','Sem novos duelos.');if(state.player.copies<1)return notify('SEM CÓPIAS','Seus Pontos de Cópia acabaram.');if(state.player.injuredMatches||state.player.energy<22)return notify('INDISPONÍVEL','Você precisa estar apto e com energia.');const target=duelTarget();if(!target)return notify('SEM ALVO','Não há outro talento disponível nesta época.');const c=clamp(Math.round(46+(overall()-target.ovr)*1.45+(state.player.form-50)*.12-(state.difficulty==='sss'?8:0)),8,92);state.player.copies--;state.player.copyUsed++;state.player.energy-=13;if(chance(c/100)){let t=state.talents.find(x=>x.id===target.talent.id);if(!t){t={...deep(target.talent),fragments:0,complete:false};state.talents.push(t)}t.fragments=clamp((t.fragments||0)+1,0,3);if(t.fragments===3&&!t.complete){t.complete=true;state.player.potential[target.talent.attribute]=99;state.player.systemLevel++;event('HABILIDADE ADQUIRIDA',`${t.name} completa. Origem: ${target.owner.name}.`)}else event('FRAGMENTO ROUBADO',`${t.name}: ${t.fragments}/3 • ${target.owner.name} • ${clubAt(target.owner,state.worldYear)}`);state.player.form=clamp(state.player.form+3,0,100)}else{state.player.morale=clamp(state.player.morale-3,0,100);event('DUELO PERDIDO',`Chance ${c}%. ${target.owner.name} protegeu seu talento.`)}save();render()}
  function match(){if(state.player.retired)return notify('APOSENTADO','Não há partidas.');if(state.player.injuredMatches)return notify('LESIONADO',`Fora por ${state.player.injuredMatches} partidas.`);if(state.player.energy<18)return notify('SEM ENERGIA','Descanse antes do jogo.');const tactic={seguro:-5,equilibrado:0,protagonista:6}[state.clubState.tactic]||0;const opp=clamp(overall()+rand(-8,10),20,96);const perf=overall()-opp+tactic+(state.player.form-50)*.12+(state.clubState.chemistry-50)*.06+rand(-9,9);const outcome=perf>=7?'win':perf<=-7?'loss':'draw';const goals=state.player.position==='Goleiro'?0:(outcome==='win'?rand(0,2):chance(.22)?1:0);const assists=chance(.24)&&goals<2?1:0;state.career.matches++;if(outcome==='win')state.career.wins++;else if(outcome==='draw')state.career.draws++;else state.career.losses++;state.career.goals+=goals;state.career.assists+=assists;const rating=clamp(5.1+perf*.08+goals*1.1+assists*.6,3,10);state.player.energy=clamp(state.player.energy-(state.clubState.tactic==='seguro'?5:state.clubState.tactic==='protagonista'?17:10),0,100);state.player.fatigue=clamp(state.player.fatigue+8,0,100);state.player.form=clamp(state.player.form+(rating>=7?4:rating<5.5?-3:1),0,100);state.player.morale=clamp(state.player.morale+(outcome==='win'?4:outcome==='loss'?-4:1),0,100);state.career.value=Math.round(state.career.value*(1+(rating-6)*.025)+goals*5000+assists*2200);if(chance(.04+state.player.fatigue/1400)){state.player.injuredMatches=rand(1,2);event('LESÃO NA PARTIDA',`Fora por ${state.player.injuredMatches} partidas.`)}event('PARTIDA',`${outcome==='win'?'Vitória':outcome==='draw'?'Empate':'Derrota'} • nota ${rating.toFixed(1)} • ${goals}G/${assists}A`);if(state.player.temporaryPenaltyMatches){state.player.temporaryPenaltyMatches--;if(!state.player.temporaryPenaltyMatches)state.player.temporaryPhysicalPenalty=0}save();render()}
  function nationalCheck(){if(state.player.age>=18&&overall()>=65&&state.player.form>=52&&!state.national.calledUp){state.national.calledUp=true;state.national.caps++;state.national.role='Convocado';event('SELEÇÃO NACIONAL',`${flagFor(state.player.nationality)} ${state.player.nationality}: convocado.`)}}
  function worldCupCheck(){const ok=state.player.age>=18&&overall()>=70&&state.player.form>=55;state.national.calledUp=ok;state.national.role=ok?'Convocado para a Copa':'Fora da Copa';state.worldCup.stage=ok?'Fase de grupos':'Não classificado';if(ok){state.national.caps++;event('COPA DO MUNDO',`${flagFor(state.player.nationality)} ${state.player.nationality}: você chegou à Copa do Mundo de ${state.worldYear}.`)}else event('COPA DO MUNDO','Você ainda não atingiu os critérios desta edição.','fail')}
  function generateOffers(){if(state.player.retired)return;const o=overall();if(o<45)return notify('MERCADO','Seu nível atual ainda não atrai grandes propostas.');const pools=o>=85?['Real Madrid','Barcelona','Manchester City']:o>=72?['Bayern München','Paris Saint-Germain','Flamengo']:['ABC Futebol Clube','Sport','Bahia'];state.market.offers=pools.map((club,i)=>({id:uid('offer'),club,salary:Math.round(Math.max(1800,o*(1200+i*250))),years:2+(i%2),role:i===0?'Disputa de titular':i===1?'Rotação':'Projeto'}));event('MERCADO',`${state.market.offers.length} propostas chegaram.`,'market');save();render()}
  function acceptOffer(id){const o=state.market.offers.find(x=>x.id===id);if(!o)return;state.player.club=o.club;state.player.salary=o.salary;state.contract.yearsLeft=o.years;state.contract.clause=Math.round(o.salary*36);state.player.loyalty=clamp(state.player.loyalty-10,0,100);state.market.offers=[];event('TRANSFERÊNCIA',`Você assinou com ${o.club}. ${money(o.salary)}/mês.`,'market');save();render()}
  function newGamePlus(){if(state.career.totalSeasons<5&&overall()<84)return notify('DESBLOQUEIO','New Game+ exige 5 temporadas ou overall 84.');const carry=state.talents.filter(t=>t.complete).map(deep);state=fresh();state.player.name='Novo Craque+';state.player.talents=carry;state.player.systemLevel=1+carry.length;for(const t of carry)if(t.attribute)state.player.potential[t.attribute]=99;event('NEW GAME+','Sua coleção de talentos atravessou a linha do tempo.');save();render()}
  function endWeek(){if(state.player.retired)return notify('APOSENTADO','Fim de carreira.');if(state.career.week>=10){endSeason();return}state.career.week++;state.career.trainingsUsed=0;state.career.phase=state.career.week<=2?'Pré-temporada':'Rodadas';state.player.energy=clamp(state.player.energy+38-Math.round(state.player.fatigue*.35),0,100);state.player.fatigue=clamp(state.player.fatigue-22,0,100);state.player.form=clamp(state.player.form+1,0,100);if(state.player.injuredMatches)state.player.injuredMatches--;if(state.player.temporaryPenaltyMatches){state.player.temporaryPenaltyMatches--;if(!state.player.temporaryPenaltyMatches)state.player.temporaryPhysicalPenalty=0}if(state.career.week===7&&[1996,2000,2004,2008,2012,2016,2020,2024].includes(state.worldYear))nationalCheck();if(state.career.week===8&&CUPS.includes(state.worldYear))worldCupCheck();save();render()}
  function endSeason(){if(state.player.retired)return;const finished=state.worldYear, o=overall();state.career.history.unshift({year:finished,age:state.player.age,overall:o,club:state.player.club,goals:state.career.goals,wins:state.career.wins});state.career.totalSeasons++;state.worldYear++;state.player.age++;state.player.birthYear=state.worldYear-state.player.age;state.career.season++;state.career.week=1;state.career.trainingsUsed=0;state.player.energy=100;state.player.fatigue=0;state.player.injuredMatches=0;state.player.temporaryPhysicalPenalty=0;state.player.temporaryPenaltyMatches=0;state.player.form=clamp(state.player.form+3,0,100);if(state.contract.yearsLeft)state.contract.yearsLeft--;if(state.player.age>=31)for(const k of PHYSICAL)state.player.attrs[k]=clamp(state.player.attrs[k]-rand(2,4),1,99);const old=state.player.category;state.player.category=categoryFor(state.player.age,overall());if(old!==state.player.category)event('PROMOÇÃO',`Você avançou para ${state.player.category}.`);if(state.career.wins>=6&&state.career.goals>=8){state.career.titles++;event('🏆 TÍTULO',`Temporada ${finished} encerrada com taça.`,'achievement')}if(state.worldYear>END_YEAR)state.player.retired=true;else generateOffers();save();render()}
  function renderTop(){q('#copyTop').textContent=state.player.copies;q('#year').textContent=state.worldYear;q('#week').textContent=state.career.week;q('#season').textContent=String(state.career.season).padStart(2,'0');q('#topFlag').textContent=flagFor(state.player.nationality);q('#topNat').textContent=state.player.nationality;q('#retiredPill').classList.toggle('show',state.player.retired)}
  function renderCareer(){const o=overall();q('#playerName').textContent=state.player.name;q('#name').textContent=state.player.name;q('#playerNat').textContent=`${flagFor(state.player.nationality)} ${state.player.nationality}`;q('#ovr').textContent=o;q('#age').textContent=state.player.age;q('#position').textContent=state.player.position;q('#category').textContent=state.player.category;q('#playerClub').textContent=state.player.club;q('#energy').textContent=`${state.player.energy}%`;q('#fatigue').textContent=`${state.player.fatigue}%`;q('#morale').textContent=`${state.player.morale}%`;q('#form').textContent=`${state.player.form}%`;q('#salary').textContent=money(state.player.salary);q('#marketValue').textContent=money(state.career.value);q('#loyalty').textContent=`${state.player.loyalty}%`;q('#starterChance').textContent=`${Math.round(clamp(48+(o-45)*.5,0,100))}%`;q('#managerTrust').textContent=`${state.clubState.managerTrust}%`;q('#trophies').textContent=state.career.titles;q('#careerContractClub').textContent=state.player.club;q('#careerContractYears').textContent=state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato';q('#agentLabel').textContent=state.contract.agent;q('#contractClause').textContent=money(state.contract.clause);q('#matchStatus').textContent=state.player.injuredMatches?`Fora ${state.player.injuredMatches} partidas.`:'Apto';const d=duelTarget(),c=d?clamp(Math.round(46+(o-d.ovr)*1.45+(state.player.form-50)*.12-(state.difficulty==='sss'?8:0)),8,92):0;q('#nextOpponent').textContent=d?.owner?.name||'Nenhum craque ativo';q('#opponentOvr').textContent=d?.ovr??'—';q('#targetTalent').textContent=d?.talent?.name||'—';q('#duelChance').textContent=d?`${c}%`:'—';q('#duelBar').style.width=d?`${c}%`:'0%';q('#tactic').value=state.clubState.tactic;q('#clubState').textContent=state.clubState.tactic==='protagonista'?'Protagonista':state.clubState.tactic==='seguro'?'Seguro':'Equilibrado';q('#record').textContent=`${state.career.wins}V ${state.career.draws}E ${state.career.losses}D`;q('#historyLog').innerHTML=state.notifications.slice(0,5).map(n=>`<div class="notice-line"><b>${esc(n.title||'Evento')}</b><span>${esc(n.body||'')}</span></div>`).join('')||'<div class="empty">O Sistema ainda está silencioso.</div>';renderAttrs();renderTalents()}
  function renderAttrs(){const html=Object.entries(ATTRS).map(([k,v])=>{const n=effective(k),temp=PHYSICAL.has(k)&&state.player.temporaryPhysicalPenalty?` • -${state.player.temporaryPhysicalPenalty} temp.`:'';return`<div class="attr"><div><span>${v}</span><small>teto ${state.player.potential[k]}${temp}</small></div><div class="bar"><i style="width:${n}%"></i></div><b>${n}</b></div>`}).join('');q('#attrs').innerHTML=html;if(q('#attrs2'))q('#attrs2').innerHTML=html}
  function renderTalents(){q('#talents').innerHTML=state.talents.length?state.talents.map(t=>`<article class="talent ${t.complete?'complete':''}"><div class="gem">✦</div><div><b>${esc(t.name)}</b><small>${t.fragments||0}/3 • ${t.complete?'PASSIVA PERMANENTE':esc(t.origin||'Craque da época')}</small></div><strong>${t.complete?'SSS':`${t.fragments||0}/3`}</strong></article>`).join(''):'<div class="empty">Nenhum talento coletado.</div>'}
  function renderTraining(){q('#trainRemain').textContent=`${MAX_TRAININGS-state.career.trainingsUsed}/${MAX_TRAININGS} sessões`;qa('[data-train]').forEach(b=>b.disabled=state.player.retired||state.player.injuredMatches>0||state.career.trainingsUsed>=MAX_TRAININGS)}
  function renderSelection(){const eligible=state.player.age>=18&&overall()>=65;q('#nationalFlag').textContent=flagFor(state.player.nationality);q('#nationalName').textContent=`Seleção ${state.player.nationality}`;q('#nationalName2').textContent=`Seleção ${state.player.nationality}`;q('#nationalRole').textContent=state.national.role;q('#nationalCaps').textContent=state.national.caps;q('#nationalOvr').textContent=Math.round(clamp(50+overall()/2,50,99));q('#selectionStatus').textContent=eligible?'Você está no radar da seleção.':'Ainda não atende aos requisitos.';q('#nextCup').textContent=CUPS.find(y=>y>=state.worldYear)||2030}
  function renderWorld(){const y=clamp(Number(q('#historyYear').value||selectedHistoryYear),START_YEAR,END_YEAR);selectedHistoryYear=y;q('#historyYearLabel').textContent=y;const term=(q('#historySearch').value||'').toLowerCase();const arr=activeStars(y).filter(p=>!term||p.name.toLowerCase().includes(term)||p.nationality.toLowerCase().includes(term)||clubAt(p,y).toLowerCase().includes(term));q('#historyCount').textContent=`${arr.length} craques encontrados`;q('#historyPlayers').innerHTML=arr.map(p=>`<article class="history-card"><div class="history-avatar">${flagFor(p.nationality)}</div><div><b>${esc(p.name)}</b><small>${esc(p.position)} • ${esc(p.nationality)} • nasceu em ${p.birthYear}</small><strong>${esc(clubAt(p,y)||'Sem clube profissional')}</strong><em>${esc(p.talent?.name||'Talento')}</em></div></article>`).join('')||'<div class="empty">Nenhum craque profissional encontrado neste ano.</div>';q('#historyYears').innerHTML=[1996,2000,2004,2008,2012,2016,2020,2024].map(n=>`<button class="year-chip ${n===y?'active':''}" data-year="${n}">${n}</button>`).join('')}
  function renderMarket(){q('#marketOffers').innerHTML=state.market.offers.length?state.market.offers.map(o=>`<article class="offer"><b>${esc(o.club)}</b><span>${esc(o.role)}</span><strong>${money(o.salary)}<small>/mês</small></strong><small>${o.years} anos</small><div><button class="btn primary" data-offer="accept" data-id="${esc(o.id)}">Assinar</button><button class="btn" data-offer="reject" data-id="${esc(o.id)}">Recusar</button></div></article>`).join(''):'<div class="empty">Nenhuma proposta aberta.</div>';q('#contractClub').textContent=state.player.club;q('#contractSalary').textContent=money(state.player.salary);q('#contractYears').textContent=state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato'}
  function renderClubs(){const term=(q('#clubSearch').value||'').toLowerCase(),country=q('#clubCountry').value,sort=q('#clubSort').value;const arr0=clubs.filter(c=>{const text=[c.name,c.city,c.state,c.country,c.short_name,...(c.aliases||[])].join(' ').toLowerCase();return(!term||text.includes(term))&&(!country||c.country===country)});arr0.sort((a,b)=>sort==='name'?String(a.name).localeCompare(String(b.name),'pt-BR'):(Number(b.relevance)||0)-(Number(a.relevance)||0)||String(a.name).localeCompare(String(b.name),'pt-BR'));q('#clubCount').textContent=`${arr0.length} clubes`;q('#clubList').innerHTML=arr0.slice(0,300).map(c=>`<article class="club-card"><b>${esc(c.short_name||c.name)}</b><span>${esc(c.name)}</span><small>${esc(c.city||'')}${c.state?` • ${esc(c.state)}`:''}<br>${esc(c.country||'')}</small><em>RELEVÂNCIA ${clamp(c.relevance||0,0,100)}</em></article>`).join('')||'<div class="empty">Nenhum clube encontrado.</div>';if(q('#clubCountry').options.length<=1&&clubs.length){const cs=[...new Set(clubs.map(c=>c.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));q('#clubCountry').innerHTML='<option value="">Todos os países</option>'+cs.map(c=>`<option>${esc(c)}</option>`).join('')}}
  function renderSystem(){q('#systemLevel').textContent=state.player.systemLevel;q('#copiesUsed').textContent=state.player.copyUsed;q('#difficultyLabel').textContent=state.difficulty.toUpperCase();q('#sysPosition').value=state.player.position;q('#difficulty').value=state.difficulty;q('#systemLog').innerHTML=state.log.slice(-9).map(x=>`<div>${esc(x)}</div>`).join('');q('#achievements').innerHTML=state.career.history.length?state.career.history.slice(0,8).map(h=>`<div class="achievement"><b>${h.year} • OVR ${h.overall}</b><span>${esc(h.club)} • ${h.goals} gols</span></div>`).join(''):'<div class="empty">Conquistas aparecerão durante a carreira.</div>';q('#ngpBtn').disabled=state.career.totalSeasons<5&&overall()<84}
  function render(){renderTop();renderCareer();renderTraining();renderSelection();renderWorld();renderMarket();renderClubs();renderSystem();applyPage()}
  function applyPage(){qa('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));qa('.page').forEach(s=>s.classList.toggle('active',s.id===`page-${page}`))}
  function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;applyPage();return}const tr=e.target.closest('[data-train]');if(tr){train(tr.dataset.train);return}if(e.target.closest('#weekBtn')){endWeek();return}if(e.target.closest('#duelBtn')){duel();return}if(e.target.closest('[data-action="match"]')){match();return}if(e.target.closest('#newGameBtn')){newGame();return}if(e.target.closest('#restBtn')){state.player.energy=clamp(state.player.energy+22,0,100);state.player.fatigue=clamp(state.player.fatigue-18,0,100);save();render();return}if(e.target.closest('#saveBtn')){save();notify('SALVO','Carreira gravada neste dispositivo.');return}const year=e.target.closest('[data-year]');if(year){q('#historyYear').value=year.dataset.year;selectedHistoryYear=Number(year.dataset.year);renderWorld();return}const offer=e.target.closest('[data-offer]');if(offer){offer.dataset.offer==='accept'?acceptOffer(offer.dataset.id):rejectOffer(offer.dataset.id);return}if(e.target.closest('#generateOffers')){generateOffers();return}if(e.target.closest('#ngpBtn')){newGamePlus();return}if(e.target.closest('#startBtn')){startCareer();return}});q('#historyYear').addEventListener('change',renderWorld);q('#historySearch').addEventListener('input',renderWorld);q('#tactic').addEventListener('change',e=>{state.clubState.tactic=e.target.value;save();render()});q('#sysPosition').addEventListener('change',e=>{if(POSITIONS.includes(e.target.value)){state.player.position=e.target.value;save();render()}});q('#difficulty').addEventListener('change',e=>{state.difficulty=e.target.value==='sss'?'sss':'normal';if(state.difficulty==='sss')state.player.copies=Math.min(state.player.copies,5);else state.player.copies=Math.max(state.player.copies,8);save();render()})}
  function normalizeHistory(d){return{players:(d?.players||[]).map((x,i)=>({id:`p${i}`,name:x[0],nationality:x[1],position:x[2],birthYear:x[3],spans:(x[4]||[]).map(s=>({from:s[0],to:s[1],club:s[2],level:s[3]==='e'?'empréstimo':'profissional'})),talent:{id:`talent-${i}`,name:x[5]?.[0]||'Talento',attribute:x[5]?.[1]==='aceleracao'?'ritmo':x[5]?.[1]||'mental',rarity:x[5]?.[2]||'Épico',passive:x[5]?.[3]||''}})),start:d?.start||1996,end:d?.end||2026}}
  async function loadData(){try{const r=await fetch('data/craques-mini.json',{cache:'no-store'});if(r.ok)historyData=normalizeHistory(await r.json())}catch(e){}try{const r=await fetch('data/clubs.generated.json',{cache:'no-store'});if(r.ok){const d=await r.json();clubs=d.clubs||d}}catch(e){}render()}
  function boot(){load();renderStartForm();bind();if(!localStorage.getItem(SAVE_KEY))q('#onboarding').classList.add('show');render();loadData()}
  function proposeContract(){}
  window.CraqueSSS={getState:()=>deep(state),newGame,save,overall};
  boot();
})();
