(()=>{
'use strict';
const SAVE_KEY='craque-sss-v8', VERSION=8, START=1996, END=2026, MAX_TRAIN=3;
const ATTR={ritmo:'Ritmo',fisico:'Físico',finalizacao:'Finalização',passe:'Passe',drible:'Drible',visao:'Visão',mental:'Mental',defesa:'Defesa',reflexo:'Reflexo'};
const PHYSICAL=new Set(['ritmo','fisico','reflexo']);
const POSITIONS=['Atacante','Ponta','Meia','Volante','Zagueiro','Goleiro'];
const COUNTRIES=[['Brasil','🇧🇷'],['Argentina','🇦🇷'],['Uruguai','🇺🇾'],['Colômbia','🇨🇴'],['Chile','🇨🇱'],['Peru','🇵🇪'],['Equador','🇪🇨'],['Paraguai','🇵🇾'],['Bolívia','🇧🇴'],['México','🇲🇽'],['Estados Unidos','🇺🇸'],['Canadá','🇨🇦'],['Costa Rica','🇨🇷'],['França','🇫🇷'],['Espanha','🇪🇸'],['Alemanha','🇩🇪'],['Itália','🇮🇹'],['Inglaterra','🏴'],['Portugal','🇵🇹'],['Países Baixos','🇳🇱'],['Bélgica','🇧🇪'],['Croácia','🇭🇷'],['Noruega','🇳🇴'],['Suécia','🇸🇪'],['Dinamarca','🇩🇰'],['Suíça','🇨🇭'],['Polônia','🇵🇱'],['Turquia','🇹🇷'],['Sérvia','🇷🇸'],['Áustria','🇦🇹'],['Marrocos','🇲🇦'],['Senegal','🇸🇳'],['Egito','🇪🇬'],['Nigéria','🇳🇬'],['Costa do Marfim','🇨🇮'],['Camarões','🇨🇲'],['Gana','🇬🇭'],['Argélia','🇩🇿'],['Tunísia','🇹🇳'],['Japão','🇯🇵'],['Coreia do Sul','🇰🇷'],['Irã','🇮🇷'],['Arábia Saudita','🇸🇦'],['Austrália','🇦🇺']];
const CUPS=[1998,2002,2006,2010,2014,2018,2022,2026];
const TRAIN={leve:{cost:16,chance:1,gain:1,fatigue:0},pesado:{cost:28,chance:.5,gain:3,fatigue:10},espartano:{cost:46,chance:.2,gain:6,fatigue:24}};
const FOCUS={Atacante:['finalizacao','ritmo','mental'],Ponta:['drible','ritmo','passe'],Meia:['passe','visao','mental'],Volante:['defesa','fisico','passe'],Zagueiro:['defesa','fisico','mental'],Goleiro:['reflexo','fisico','mental']};
const RIVAL_NAMES=[['Lucas Vidal','Ponta'],['Gabriel Rocha','Meia'],['Caio Mendes','Atacante'],['Enzo Martins','Ponta']];
const MEDIA=['A imprensa começou a notar sua evolução.','O treinador elogiou sua disciplina no treino.','Um observador estrangeiro apareceu na arquibancada.','Seu rival começou a estudar seus movimentos.','A torcida quer saber até onde você pode chegar.'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const chance=p=>Math.random()<p;
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Math.max(0,Math.round(v||0)));
const flag=n=>COUNTRIES.find(c=>c[0]===n)?.[1]||'🌎';
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
let history={players:[],start:START,end:END}, clubs=[]; let page='carreira', toastTimer=0;
function fresh(){const attrs={ritmo:24,fisico:23,finalizacao:22,passe:25,drible:26,visao:24,mental:21,defesa:21,reflexo:20};return{version:VERSION,worldYear:START,difficulty:'normal',player:{name:'Novo Craque',nationality:'Brasil',age:15,birthYear:1981,position:'Ponta',category:'Sub-15',club:'Academia Local',salary:0,energy:100,fatigue:0,morale:72,form:68,loyalty:55,injuredMatches:0,temporaryPhysicalPenalty:0,temporaryPenaltyMatches:0,copies:8,systemLevel:1,copyUsed:0,retired:false,personality:{discipline:55,ambition:55,popularity:5}},career:{season:1,week:1,phase:'Pré-temporada',trainingsUsed:0,restUsed:false,playedWeek:false,wins:0,draws:0,losses:0,goals:0,assists:0,matches:0,decisive:0,titles:0,value:1000,totalSeasons:0,history:[],seasonStats:{wins:0,draws:0,losses:0,goals:0,assists:0,matches:0,points:0}},clubState:{tactic:'equilibrado',chemistry:55,managerTrust:45,starterChance:48},contract:{yearsLeft:0,agent:'Conservador',clause:0},market:{offers:[]},national:{calledUp:false,caps:0,goals:0,assists:0,titles:0,role:'Fora da convocação'},worldCup:{stage:'Não classificado',year:null,round:0},talents:[],rivals:RIVAL_NAMES.map((r,i)=>({id:`r${i}`,name:r[0],position:r[1],ovr:34+i*5,relationship:0,wins:0,losses:0})),notifications:[{title:'DESPERTAR',body:'1996. O Sistema encontrou você. O mundo ainda não sabe seu nome.'}],log:['[SISTEMA] Linha do tempo sincronizada em 1996.'],achievements:[]}};
let state=fresh();
function normalize(s){const f=fresh();if(!s||s.version!==VERSION)return f;const out={...f,...s,player:{...f.player,...s.player},career:{...f.career,...s.career,seasonStats:{...f.career.seasonStats,...(s.career?.seasonStats||{})}},clubState:{...f.clubState,...s.clubState},contract:{...f.contract,...s.contract},market:{...f.market,...s.market},national:{...f.national,...s.national},worldCup:{...f.worldCup,...s.worldCup}};out.player.attrs={...f.player.attrs,...(s.player?.attrs||{})};out.player.potential={...f.player.potential,...(s.player?.potential||{})};out.player.age=clamp(out.player.age,15,55);out.worldYear=clamp(out.worldYear,START,END);out.player.energy=clamp(out.player.energy,0,100);out.player.fatigue=clamp(out.player.fatigue,0,100);out.player.morale=clamp(out.player.morale,0,100);out.player.form=clamp(out.player.form,0,100);out.player.loyalty=clamp(out.player.loyalty,0,100);out.player.copies=clamp(out.player.copies,0,999);out.player.injuredMatches=clamp(out.player.injuredMatches,0,10);out.player.temporaryPhysicalPenalty=clamp(out.player.temporaryPhysicalPenalty,0,8);out.player.temporaryPenaltyMatches=clamp(out.player.temporaryPenaltyMatches,0,4);out.career.trainingsUsed=clamp(out.career.trainingsUsed,0,MAX_TRAIN);out.career.restUsed=!!out.career.restUsed;out.career.playedWeek=!!out.career.playedWeek;out.talents=Array.isArray(out.talents)?out.talents:[];out.rivals=Array.isArray(out.rivals)?out.rivals:f.rivals;out.notifications=Array.isArray(out.notifications)?out.notifications.slice(0,60):[];out.log=Array.isArray(out.log)?out.log.slice(-60):f.log;out.achievements=Array.isArray(out.achievements)?out.achievements:[];return out}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));return true}catch{return false}}
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');state=normalize(x)}catch{state=fresh()}}
function notify(t,m){const el=$('#toast');if(!el)return;el.innerHTML=`<b>${esc(t)}</b><span>${esc(m)}</span>`;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
function event(t,m){state.notifications.unshift({id:uid('n'),title:t,body:m,year:state.worldYear});state.notifications=state.notifications.slice(0,60);notify(t,m)}
function log(m,type='SISTEMA'){state.log.push(`[${type}] ${m}`);state.log=state.log.slice(-60)}
function overall(){const keys=Object.keys(ATTR);let base=keys.reduce((s,k)=>s+effective(k),0)/keys.length;const pos=state.player.position==='Goleiro'?((effective('reflexo')-40)*.2):((effective('finalizacao')+effective('drible')-80)*.03);return Math.round(clamp(base+pos+state.talents.filter(t=>t.complete).length*1.5,1,99))}
function effective(k){const v=clamp(state.player.attrs[k],1,99);return PHYSICAL.has(k)?clamp(v-state.player.temporaryPhysicalPenalty,1,99):v}
function category(){const a=state.player.age,o=overall();if(a>=19&&o>=84)return'Seleção Principal';if(a>=18&&o>=72)return'Europa';if(a>=17&&o>=55)return'Estreante Profissional';if(a>=16&&o>=40)return'Sub-17';return'Sub-15'}
function activeStars(year){return history.players.filter(p=>p.spans.some(s=>s.level==='profissional'&&year>=s.from&&year<=s.to&&year>=p.birthYear+15))}
function clubAt(p,y){return p.spans.filter(s=>y>=s.from&&y<=s.to).map(s=>`${s.club}${s.level==='empréstimo'?' (empréstimo)':''}`).join(' / ')||'Sem clube profissional'}
function duelTarget(){const completed=new Set(state.talents.filter(t=>t.complete).map(t=>t.id));const targets=activeStars(state.worldYear).filter(p=>!completed.has(p.talent.id));if(!targets.length)return null;const p=targets[(state.career.week-1)%targets.length],ageGap=Math.max(0,state.worldYear-p.birthYear-15);return{owner:p,talent:p.talent,ovr:clamp(34+Math.round(ageGap*1.6),25,96)}}
function train(type){if(state.player.retired)return notify('APOSENTADO','A carreira já terminou.');if(state.player.injuredMatches)return notify('LESIONADO',`Você está fora por ${state.player.injuredMatches} partida(s).`);if(state.career.trainingsUsed>=MAX_TRAIN)return notify('LIMITE SEMANAL','Você já usou 3 sessões nesta semana.');const spec=TRAIN[type];if(!spec)return;if(state.player.energy<spec.cost)return notify('ENERGIA BAIXA','Descanse antes de treinar.');state.career.trainingsUsed++;state.player.energy-=spec.cost;const pool=FOCUS[state.player.position]||FOCUS.Ponta,attr=pool[rand(0,pool.length-1)],before=overall(),success=chance(spec.chance);if(success){const gain=Math.min(spec.gain,Math.max(0,state.player.potential[attr]-state.player.attrs[attr]));state.player.attrs[attr]=clamp(state.player.attrs[attr]+gain,1,99);state.player.form=clamp(state.player.form+(gain?2:0),0,100);log(`${spec.label||type}: +${gain} ${ATTR[attr]}.`,'TREINO');event('TREINO',`Sessão ${type}: ${gain?`+${gain} ${ATTR[attr]}`:'atributo já no teto.'}`)}else{state.player.morale=clamp(state.player.morale-(type==='espartano'?5:2),0,100);event('TREINO FALHOU',`A sessão ${type} não gerou evolução.`)}state.player.fatigue=clamp(state.player.fatigue+spec.fatigue,0,100);if(type==='pesado'&&chance(.15)){state.player.temporaryPhysicalPenalty=rand(2,4);state.player.temporaryPenaltyMatches=1;event('FADIGA FÍSICA',`- ${state.player.temporaryPhysicalPenalty} nos atributos físicos por 1 partida.`)}if(type==='espartano'&&chance(.25)){state.player.injuredMatches=rand(3,10);state.player.energy=8;event('LESÃO GRAVE',`Você ficará fora por ${state.player.injuredMatches} partidas.`)}if(overall()-before>=5)event('REAÇÃO DO MUNDO',`Seu OVR saltou de ${before} para ${overall()}. A imprensa começou a desconfiar.`);save();render()}
function duel(){if(state.player.retired)return notify('APOSENTADO','O Sistema não cria novos duelos.');if(state.player.copies<1)return notify('SEM CP','Você não tem Pontos de Cópia.');if(state.career.playedWeek&&state.career.week%2===0)return notify('DUELO ENCERRADO','Nesta semana você já comprometeu toda sua concentração com a partida.');if(state.player.injuredMatches||state.player.energy<22)return notify('INDISPONÍVEL','Você precisa estar apto e com energia.');const d=duelTarget();if(!d)return notify('SEM ALVO','Nenhum talento profissional válido nesta época.');const c=clamp(Math.round(46+(overall()-d.ovr)*1.45+(state.player.form-50)*.13+(state.player.morale-50)*.06-(state.difficulty==='sss'?8:0)),8,92);state.player.copies--;state.player.copyUsed++;state.player.energy=clamp(state.player.energy-13,0,100);const rival=state.rivals.find(r=>r.name===d.owner.name);if(chance(c/100)){let t=state.talents.find(x=>x.id===d.talent.id);if(!t){t={...clone(d.talent),fragments:0,complete:false,level:1};state.talents.push(t)}t.fragments=clamp((t.fragments||0)+1,0,3);if(rival){rival.relationship-=6;rival.losses++}if(t.fragments===3&&!t.complete){t.complete=true;t.level=2;state.player.potential[d.talent.attribute]=99;state.player.systemLevel++;event('HABILIDADE ADQUIRIDA',`${t.name} completa. Origem: ${d.owner.name}.`);unlock(`talent-${t.id}`,`Talento completo: ${t.name}`)}else event('FRAGMENTO ROUBADO',`${t.name}: ${t.fragments}/3 • ${d.owner.name} • ${clubAt(d.owner,state.worldYear)}`);state.player.form=clamp(state.player.form+3,0,100)}else{if(rival){rival.relationship+=5;rival.wins++}state.player.morale=clamp(state.player.morale-3,0,100);event('DUELO PERDIDO',`Chance ${c}%. ${d.owner.name} protegeu o talento.`)}save();render()}
function match(mode){if(state.player.retired)return notify('APOSENTADO','Não há partidas após a aposentadoria.');if(state.career.playedWeek)return notify('PARTIDA JÁ JOGADA','Você só pode jogar uma partida por semana.');if(state.player.injuredMatches)return notify('LESIONADO',`Você está fora por ${state.player.injuredMatches} partidas.`);if(state.player.energy<18)return notify('SEM ENERGIA','Descanse antes do jogo.');const approach=mode||state.clubState.tactic;state.clubState.tactic=approach;const tactic={seguro:-5,equilibrado:0,protagonista:6}[approach]||0;const rivalLevel=clamp(overall()+rand(-9,9),20,96);const performance=overall()-rivalLevel+tactic+(state.player.form-50)*.12+(state.clubState.chemistry-50)*.06-rand(0,6);const outcome=performance>=7?'win':performance<=-7?'loss':'draw';const starter=Math.random()<clamp(.35+(overall()-40)*.012+state.clubState.managerTrust*.002,0.25,0.96);const goals=starter&&state.player.position!=='Goleiro'?(outcome==='win'?rand(0,2):chance(.18)?1:0):0;const assists=starter&&chance(.22)&&goals<2?1:0;const rating=clamp(5.1+performance*.08+goals*1.15+assists*.65,3,10);state.career.playedWeek=true;state.career.matches++;state.career.seasonStats.matches++;if(outcome==='win'){state.career.wins++;state.career.seasonStats.wins++;state.career.seasonStats.points+=3}else if(outcome==='draw'){state.career.draws++;state.career.seasonStats.draws++;state.career.seasonStats.points++}else{state.career.losses++;state.career.seasonStats.losses++}state.career.goals+=goals;state.career.assists+=assists;state.career.seasonStats.goals+=goals;state.career.seasonStats.assists+=assists;if(goals||assists)state.career.decisisive=(state.career.decisisive||0)+1;state.player.energy=clamp(state.player.energy-(approach==='seguro'?5:approach==='protagonista'?17:10),0,100);state.player.fatigue=clamp(state.player.fatigue+8,0,100);state.player.form=clamp(state.player.form+(rating>=7?4:rating<5.5?-3:1),0,100);state.player.morale=clamp(state.player.morale+(outcome==='win'?4:outcome==='loss'?-4:1),0,100);state.clubState.managerTrust=clamp(state.clubState.managerTrust+(rating>=7?3:-2),0,100);state.clubState.chemistry=clamp(state.clubState.chemistry+(outcome==='win'?2:-1),0,100);state.career.value=Math.round(state.career.value*(1+(rating-6)*.025)+goals*5000+assists*2200);if(chance(.035+state.player.fatigue/1400)){state.player.injuredMatches=rand(1,2);event('LESÃO NA PARTIDA',`Fora por ${state.player.injuredMatches} partidas.`)}event('PARTIDA',`${outcome==='win'?'Vitória':outcome==='draw'?'Empate':'Derrota'} • nota ${rating.toFixed(1)} • ${goals}G/${assists}A`);save();render()}
function callSelection(){const eligible=state.player.age>=18&&overall()>=65&&state.player.form>=52;if(eligible&&!state.national.calledUp){state.national.calledUp=true;state.national.role='Convocado';state.national.caps++;event('SELEÇÃO NACIONAL',`${flag(state.player.nationality)} ${state.player.nationality}: você foi convocado.`);unlock('national-debut','Estreia na seleção','Primeira convocação internacional.')}}
function cupCheck(){const year=CUPS.find(y=>y>=state.worldYear);if(!year||year!==state.worldYear)return;const eligible=state.player.age>=18&&overall()>=70&&state.player.form>=55;state.worldCup.year=year;state.worldCup.stage=eligible?'Fase de grupos':'Fora da Copa';state.worldCup.round=eligible?1:0;if(!eligible)return event('COPA DO MUNDO',`Você não atingiu os critérios para a Copa de ${year}.`);state.national.calledUp=true;state.national.caps++;const rounds=Math.max(1,Math.min(4,Math.round((overall()+state.player.form+state.player.morale)/70)));state.worldCup.round=rounds;const won=rounds>=4&&chance(.28);if(won){state.worldCup.stage='CAMPEÃO';state.worldCup.round=7;state.national.titles++;event('🏆 CAMPEÃO DO MUNDO',`${flag(state.player.nationality)} ${state.player.nationality}: você levantou a taça em ${year}.`);unlock(`world-${year}`,`Campeão mundial ${year}`)}else{const stages=['Fase de grupos','Oitavas de final','Quartas de final','Semifinal'];state.worldCup.stage=stages[Math.max(0,Math.min(3,rounds-1))];event('COPA DO MUNDO',`${flag(state.player.nationality)} ${state.player.nationality}: campanha encerrada em ${state.worldCup.stage}.`)}}
function generateOffers(){if(state.player.retired)return;const o=overall();if(o<42)return notify('MERCADO','Seu nível ainda é baixo para grandes propostas.');const top=o>=85?['Real Madrid','Barcelona','Manchester City','Bayern München']:o>=72?['Liverpool','Paris Saint-Germain','Milan','Flamengo']:['ABC Futebol Clube','Sport','Bahia','Fortaleza'];const bonus=state.contract.agent==='Agressivo'?1.15:.98;state.market.offers=top.slice(0,3).map((club,i)=>({id:uid('offer'),club,salary:Math.round(Math.max(2000,o*(900+i*280))*bonus),years:2+(i%2),role:i===0?'Projeto de estrela':i===1?'Disputa de titular':'Rotação'}));event('MERCADO',`${state.market.offers.length} propostas disponíveis.`);save();render()}
function acceptOffer(id){const o=state.market.offers.find(x=>x.id===id);if(!o)return;state.player.club=o.club;state.player.salary=o.salary;state.contract.yearsLeft=o.years;state.contract.clause=Math.round(o.salary*36);state.player.loyalty=clamp(state.player.loyalty-8,0,100);state.market.offers=[];event('TRANSFERÊNCIA',`Contrato assinado com ${o.club}. ${money(o.salary)}/mês.`);unlock(`club-${o.club}`,'Nova casa: '+o.club);save();render()}
function rejectOffer(id){state.market.offers=state.market.offers.filter(o=>o.id!==id);save();render()}
function rest(){if(state.career.restUsed)return notify('DESCANSO USADO','Você já descansou nesta semana.');state.career.restUsed=true;state.player.energy=clamp(state.player.energy+28,0,100);state.player.fatigue=clamp(state.player.fatigue-20,0,100);state.player.form=clamp(state.player.form+1,0,100);event('RECUPERAÇÃO','Você ganhou energia e reduziu a fadiga.');save();render()}
function endWeek(){if(state.player.retired)return notify('APOSENTADO','Fim da carreira.');if(!state.career.playedWeek&&state.career.week>2){state.player.form=clamp(state.player.form-1,0,100);log('Você pulou a partida da semana.','ESCOLHA')}if(state.career.week>=10){endSeason();return}state.career.week++;state.career.trainingsUsed=0;state.career.restUsed=false;state.career.playedWeek=false;state.career.phase=state.career.week<=2?'Pré-temporada':'Rodadas';state.player.energy=clamp(state.player.energy+38-Math.round(state.player.fatigue*.35),0,100);state.player.fatigue=clamp(state.player.fatigue-22,0,100);state.player.form=clamp(state.player.form+1,0,100);if(state.player.injuredMatches)state.player.injuredMatches--;if(state.player.temporaryPenaltyMatches){state.player.temporaryPenaltyMatches--;if(!state.player.temporaryPenaltyMatches)state.player.temporaryPhysicalPenalty=0}if(state.career.week===6)callSelection();if(state.career.week===8)cupCheck();save();render()}
function endSeason(){const finished=state.worldYear;const ss=clone(state.career.seasonStats);state.career.history.unshift({year:finished,age:state.player.age,overall:overall(),club:state.player.club,goals:ss.goals,assists:ss.assists,wins:ss.wins,points:ss.points});state.career.totalSeasons++;if(ss.wins>=6&&ss.points>=18){state.career.titles++;event('🏆 TÍTULO DE TEMPORADA',`Você terminou ${finished} como campeão.`);unlock(`title-${finished}`,`Campeão em ${finished}`)}state.worldYear++;state.player.age++;state.player.birthYear=state.worldYear-state.player.age;state.career.season++;state.career.week=1;state.career.trainingsUsed=0;state.career.restUsed=false;state.career.playedWeek=false;state.career.seasonStats={wins:0,draws:0,losses:0,goals:0,assists:0,matches:0,points:0};state.player.energy=100;state.player.fatigue=0;state.player.injuredMatches=0;state.player.temporaryPhysicalPenalty=0;state.player.temporaryPenaltyMatches=0;state.player.form=clamp(state.player.form+3,0,100);if(state.contract.yearsLeft)state.contract.yearsLeft--;if(state.player.age>=31)for(const k of PHYSICAL)state.player.attrs[k]=clamp(state.player.attrs[k]-rand(2,4),1,99);const old=state.player.category;state.player.category=category();if(old!==state.player.category)event('PROMOÇÃO',`${old} → ${state.player.category}.`);state.rivals.forEach(r=>{r.ovr=clamp(r.ovr+rand(1,4),30,98);r.relationship=clamp(r.relationship-rand(0,4),-100,100)});if(state.worldYear>END){state.player.retired=true;event('FIM DE CARREIRA',`Você encerrou a carreira aos ${state.player.age-1} anos.`);unlock('retired','Lenda do futebol','Carreira encerrada.')}else generateOffers();save();render()}
function unlock(id,title){if(state.achievements.some(a=>a.id===id))return;state.achievements.push({id,title,at:Date.now()});event('CONQUISTA',title)}
function setAgent(agent){state.contract.agent=agent;state.player.personality.ambition=agent==='Agressivo'?75:50;event('EMPRESÁRIO',`Perfil alterado para ${agent}.`);save();render()}
function newGamePlus(){if(state.career.totalSeasons<5&&overall()<84)return notify('BLOQUEADO','New Game+ exige 5 temporadas ou OVR 84.');const carry=state.talents.filter(t=>t.complete).map(clone);state=fresh();state.player.name='Novo Craque+';state.player.talents=carry;state.player.systemLevel=1+carry.length;carry.forEach(t=>{if(t.attribute)state.player.potential[t.attribute]=99});event('NEW GAME+','Seu conhecimento atravessou a linha do tempo.');save();render()}
function newGame(){if(window.confirm('Começar uma nova carreira em 1996? O save atual será substituído.')){localStorage.removeItem(SAVE_KEY);state=fresh();save();render();const m=$('#onboarding');if(m)m.classList.add('show')}}
function startCareer(){const name=($('#startName')?.value||'Novo Craque').trim().slice(0,24)||'Novo Craque';const nat=$('#startNationality')?.value||'Brasil';const pos=$('#startPosition')?.value||'Ponta';const diff=$('#startDifficulty')?.value==='sss'?'sss':'normal';state=fresh();state.player.name=name;state.player.nationality=COUNTRIES.some(c=>c[0]===nat)?nat:'Brasil';state.player.position=POSITIONS.includes(pos)?pos:'Ponta';state.difficulty=diff;if(diff==='sss')state.player.copies=5;state.player.category=category();save();$('#onboarding')?.classList.remove('show');event('SISTEMA ATIVO',`${flag(state.player.nationality)} ${state.player.nationality} • ${state.player.position} • ${diff.toUpperCase()}`);render()}
function injectPanels(){if(!$('#rivalPanel')){$('#page-carreira .card:last-child')?.insertAdjacentHTML('afterend','<article id="rivalPanel" class="card extra-card"><div class="eyebrow">RIVALIDADE</div><div id="rivalBody"></div></article>')}if(!$('#financePanel')){$('#page-carreira .grid3 aside:last-child')?.insertAdjacentHTML('afterbegin','<article id="financePanel" class="card extra-card"><div class="eyebrow">FINANÇAS</div><div class="kv"><span>Patrimônio</span><b id="wealth">R$ 1.000</b></div><div class="kv"><span>Empresário</span><b id="financeAgent">Conservador</b></div><div class="kv"><span>Popularidade</span><b id="popularity">5%</b></div></article>')}if(!$('#cupPanel')){$('#page-selecao .grid2')?.insertAdjacentHTML('beforebegin','<article id="cupPanel" class="card extra-card"><div class="eyebrow">COPA DO MUNDO</div><div class="system-stats"><div><span>Próxima edição</span><b id="cupYear">1998</b></div><div><span>Status</span><b id="cupStage">Não classificado</b></div><div><span>Melhor campanha</span><b id="cupBest">—</b></div></div></article>')}if(!$('#hallPanel')){$('#page-sistema .grid2')?.insertAdjacentHTML('afterend','<article id="hallPanel" class="card extra-card"><div class="eyebrow">HALL DA FAMA</div><div id="hallBody"></div></article>')}}
function renderTop(){const by=id=>$('#'+id);by('copyTop').textContent=state.player.copies;by('year').textContent=state.worldYear;by('week').textContent=state.career.week;by('season').textContent=String(state.career.season).padStart(2,'0');by('topFlag').textContent=flag(state.player.nationality);by('topNat').textContent=state.player.nationality;by('retiredPill').classList.toggle('show',state.player.retired)}
function renderCareer(){const o=overall();$('#playerName').textContent=state.player.name;$('#name').textContent=state.player.name;$('#playerNat').textContent=`${flag(state.player.nationality)} ${state.player.nationality}`;$('#ovr').textContent=o;$('#age').textContent=state.player.age;$('#position').textContent=state.player.position;state.player.category=category();$('#category').textContent=state.player.category;$('#playerClub').textContent=state.player.club;$('#energy').textContent=`${state.player.energy}%`;$('#fatigue').textContent=`${state.player.fatigue}%`;$('#morale').textContent=`${state.player.morale}%`;$('#form').textContent=`${state.player.form}%`;$('#salary').textContent=money(state.player.salary);$('#marketValue').textContent=money(state.career.value);$('#loyalty').textContent=`${state.player.loyalty}%`;$('#starterChance').textContent=`${Math.round(clamp(35+(o-40)*1.2+state.clubState.managerTrust*.2,0,98))}%`;$('#managerTrust').textContent=`${state.clubState.managerTrust}%`;$('#trophies').textContent=state.career.titles;$('#careerContractClub').textContent=state.player.club;$('#careerContractYears').textContent=state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato';$('#agentLabel').textContent=state.contract.agent;$('#financeAgent').textContent=state.contract.agent;$('#contractClause').textContent=money(state.contract.clause);$('#matchStatus').textContent=state.player.injuredMatches?`Fora ${state.player.injuredMatches} partidas.`:state.career.playedWeek?'Partida jogada':'Apto';const d=duelTarget(),c=d?clamp(Math.round(46+(o-d.ovr)*1.45+(state.player.form-50)*.13+(state.player.morale-50)*.06-(state.difficulty==='sss'?8:0)),8,92):0;$('#nextOpponent').textContent=d?.owner?.name||'Nenhum craque ativo';$('#opponentOvr').textContent=d?.ovr??'—';$('#targetTalent').textContent=d?.talent?.name||'—';$('#duelChance').textContent=d?`${c}%`:'—';$('#duelBar').style.width=d?`${c}%`:'0';$('#tactic').value=state.clubState.tactic;$('#clubState').textContent=state.clubState.tactic==='protagonista'?'Protagonista':state.clubState.tactic==='seguro'?'Seguro':'Equilibrado';$('#record').textContent=`${state.career.wins}V ${state.career.draws}E ${state.career.losses}D`;$('#historyLog').innerHTML=state.notifications.slice(0,6).map(n=>`<div class="notice-line"><b>${esc(n.title||'Evento')}</b><span>${esc(n.body||'')}</span></div>`).join('');renderAttrs();renderTalents();const rivals=state.rivals.slice(0,4).sort((a,b)=>b.relationship-a.relationship);$('#rivalBody').innerHTML=rivals.map(r=>`<div class="rival-row"><div><b>${esc(r.name)}</b><small>${esc(r.position)} • OVR ${r.ovr}</small></div><span>${r.relationship>=25?'🤝':r.relationship<=-25?'⚔':'•'} ${r.relationship}</span></div>`).join('');$('#wealth').textContent=money(state.career.value+Math.round(state.player.salary*state.career.totalSeasons*.55));$('#popularity').textContent=`${clamp(5+state.career.goals*.35+state.career.titles*8+state.career.matches*.02,0,100).toFixed(0)}%`}
function renderAttrs(){const html=Object.entries(ATTR).map(([k,v])=>{const n=effective(k),temp=PHYSICAL.has(k)&&state.player.temporaryPhysicalPenalty?` • -${state.player.temporaryPhysicalPenalty} temp.`:'';return`<div class="attr"><div><span>${v}</span><small>teto ${state.player.potential[k]}${temp}</small></div><div class="bar"><i style="width:${n}%"></i></div><b>${n}</b></div>`}).join('');$('#attrs').innerHTML=html;if($('#attrs2'))$('#attrs2').innerHTML=html}
function renderTalents(){$('#talents').innerHTML=state.talents.length?state.talents.map(t=>`<article class="talent ${t.complete?'complete':''}"><div class="gem">✦</div><div><b>${esc(t.name)}</b><small>${t.fragments||0}/3 • ${t.complete?'PASSIVA PERMANENTE':esc(t.origin||'Craque')}</small></div><strong>${t.complete?'SSS':`${t.fragments||0}/3`}</strong></article>`).join(''):'<div class="empty">Nenhum talento coletado.</div>'}
function renderTraining(){$('#trainRemain').textContent=`${MAX_TRAIN-state.career.trainingsUsed}/${MAX_TRAIN} sessões`;$$('[data-train]').forEach(b=>b.disabled=state.player.retired||!!state.player.injuredMatches||state.career.trainingsUsed>=MAX_TRAIN);const p=$('[data-train="pesado"]')?.closest('.session');const s=$('[data-train="espartano"]')?.closest('.session');if(p){const t=p.querySelector('small');if(t)t.textContent='+3 • 50% sucesso • 15% chance de fadiga física temporária'}if(s){const t=s.querySelector('small');if(t)t.textContent='+6 • 20% sucesso • 25% lesão grave por 3–10 partidas'}}
function renderSelection(){const next=CUPS.find(y=>y>=state.worldYear)||2030;$('#nationalFlag').textContent=flag(state.player.nationality);$('#nationalName').textContent=`Seleção ${state.player.nationality}`;$('#nationalName2').textContent=`Seleção ${state.player.nationality}`;$('#nationalRole').textContent=state.national.role;$('#nationalCaps').textContent=state.national.caps;$('#nationalOvr').textContent=Math.round(clamp(50+overall()/2,50,99));$('#selectionStatus').textContent=state.player.age>=18&&overall()>=65?'Você está no radar da seleção.':'Ainda não atende aos requisitos.';$('#nextCup').textContent=next;$('#cupYear').textContent=state.worldCup.year||next;$('#cupStage').textContent=state.worldCup.stage;$('#cupBest').textContent=state.national.titles?`${state.national.titles} título(s)`:'—'}
function renderWorld(){const y=clamp(Number($('#historyYear').value||START),START,END);$('#historyYearLabel').textContent=y;const term=($('#historySearch').value||'').toLowerCase();const arr=activeStars(y).filter(p=>!term||p.name.toLowerCase().includes(term)||p.nationality.toLowerCase().includes(term)||clubAt(p,y).toLowerCase().includes(term));$('#historyCount').textContent=String(arr.length);$('#historyPlayers').innerHTML=arr.map(p=>`<article class="history-card"><div class="history-avatar">${flag(p.nationality)}</div><div><b>${esc(p.name)}</b><small>${esc(p.position)} • ${esc(p.nationality)} • nasceu em ${p.birthYear}</small><strong>${esc(clubAt(p,y))}</strong><em>${esc(p.talent?.name||'Talento')}</em></div></article>`).join('')||'<div class="empty">Nenhum craque profissional encontrado neste ano.</div>';$('#historyYears').innerHTML=[1996,2000,2004,2008,2012,2016,2020,2024].map(n=>`<button class="year-chip ${n===y?'active':''}" data-year="${n}">${n}</button>`).join('')}
function renderMarket(){$('#marketOffers').innerHTML=state.market.offers.length?state.market.offers.map(o=>`<article class="offer"><b>${esc(o.club)}</b><span>${esc(o.role)}</span><strong>${money(o.salary)}<small>/mês</small></strong><small>${o.years} anos</small><div><button class="btn primary" data-offer="accept" data-id="${esc(o.id)}">Assinar</button><button class="btn" data-offer="reject" data-id="${esc(o.id)}">Recusar</button></div></article>`).join(''):'<div class="empty">Nenhuma proposta. Busque interesse quando sua forma justificar.</div>';$('#contractClub').textContent=state.player.club;$('#contractSalary').textContent=money(state.player.salary);$('#contractYears').textContent=state.contract.yearsLeft?`${state.contract.yearsLeft} anos`:'Sem contrato';$$('[data-agent]').forEach(b=>b.classList.toggle('active',b.dataset.agent===state.contract.agent))}
function renderClubs(){const term=($('#clubSearch').value||'').toLowerCase(),country=$('#clubCountry').value,sort=$('#clubSort').value;const arr=clubs.filter(c=>{const txt=[c.name,c.city,c.state,c.country,c.short_name,...(c.aliases||[])].join(' ').toLowerCase();return(!term||txt.includes(term))&&(!country||c.country===country)}).sort((a,b)=>sort==='name'?String(a.name).localeCompare(String(b.name),'pt-BR'):(Number(b.relevance)||0)-(Number(a.relevance)||0)||String(a.name).localeCompare(String(b.name),'pt-BR'));$('#clubCount').textContent=`${arr.length} clubes`;$('#clubList').innerHTML=arr.slice(0,300).map(c=>`<article class="club-card"><b>${esc(c.short_name||c.name)}</b><span>${esc(c.name)}</span><small>${esc(c.city||'')}${c.state?' • '+esc(c.state):''}<br>${esc(c.country||'')}</small><em>RELEVÂNCIA ${clamp(c.relevance||0,0,100)}</em></article>`).join('')||'<div class="empty">Nenhum clube encontrado.</div>';if($('#clubCountry').options.length<=1&&clubs.length){const cs=[...new Set(clubs.map(c=>c.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#clubCountry').innerHTML='<option value="">Todos os países</option>'+cs.map(c=>`<option>${esc(c)}</option>`).join('')}}
function renderSystem(){const achievements=state.achievements.slice(-10).reverse();$('#systemLevel').textContent=state.player.systemLevel;$('#copiesUsed').textContent=state.player.copyUsed;$('#difficultyLabel').textContent=state.difficulty.toUpperCase();$('#sysPosition').value=state.player.position;$('#difficulty').value=state.difficulty;$('#systemLog').innerHTML=state.log.slice(-9).map(x=>`<div>${esc(x)}</div>`).join('');$('#achievements').innerHTML=achievements.length?achievements.map(a=>`<div class="achievement"><b>${esc(a.title)}</b><span>${new Date(a.at||Date.now()).toLocaleDateString('pt-BR')}</span></div>`).join(''):'<div class="empty">As conquistas aparecerão durante a carreira.</div>';$('#ngpBtn').disabled=state.career.totalSeasons<5&&overall()<84;$('#hallBody').innerHTML=`<div class="hall-grid"><div><b>${state.career.matches}</b><span>jogos</span></div><div><b>${state.career.goals}</b><span>gols</span></div><div><b>${state.career.assists}</b><span>assistências</span></div><div><b>${state.career.titles}</b><span>títulos</span></div><div><b>${overall()}</b><span>OVR atual</span></div></div>`}
function render(){injectPanels();renderTop();renderCareer();renderTraining();renderSelection();renderWorld();renderMarket();renderClubs();renderSystem();applyPage()}
function applyPage(){$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(s=>s.classList.toggle('active',s.id===`page-${page}`))}
function populateStart(){const ns=$('#startNationality');const ps=$('#startPosition');if(ns&&!ns.options.length)ns.innerHTML=COUNTRIES.map(c=>`<option value="${esc(c[0])}">${c[1]} ${esc(c[0])}</option>`).join('');if(ps&&!ps.options.length)ps.innerHTML=POSITIONS.map(p=>`<option>${esc(p)}</option>`).join('');if(ns)ns.value='Brasil';if(ps)ps.value='Ponta'}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;applyPage();return}const tr=e.target.closest('[data-train]');if(tr){train(tr.dataset.train);return}const yr=e.target.closest('[data-year]');if(yr){$('#historyYear').value=yr.dataset.year;renderWorld();return}const offer=e.target.closest('[data-offer]');if(offer){offer.dataset.offer==='accept'?acceptOffer(offer.dataset.id):rejectOffer(offer.dataset.id);return}const ag=e.target.closest('[data-agent]');if(ag){setAgent(ag.dataset.agent);return}if(e.target.closest('#weekBtn')){endWeek();return}if(e.target.closest('#duelBtn')){duel();return}const matchBtn=e.target.closest('[data-action="match"]');if(matchBtn){$$('[data-action="match"]').forEach(b=>b.classList.remove('selected'));matchBtn.classList.add('selected');match(matchBtn.dataset.approach);return}if(e.target.closest('#newGameBtn')){newGame();return}if(e.target.closest('#restBtn')){rest();return}if(e.target.closest('#saveBtn')){save();notify('SALVO','Carreira gravada neste dispositivo.');return}if(e.target.closest('#generateOffers')){generateOffers();return}if(e.target.closest('#ngpBtn')){newGamePlus();return}if(e.target.closest('#startBtn')){startCareer();return}});$('#historyYear').addEventListener('change',renderWorld);$('#historySearch').addEventListener('input',renderWorld);$('#clubSearch').addEventListener('input',renderClubs);$('#clubCountry').addEventListener('change',renderClubs);$('#clubSort').addEventListener('change',renderClubs);$('#tactic').addEventListener('change',e=>{state.clubState.tactic=e.target.value;save();render()});$('#sysPosition').addEventListener('change',e=>{if(POSITIONS.includes(e.target.value)){state.player.position=e.target.value;save();render()}});$('#difficulty').addEventListener('change',e=>{state.difficulty=e.target.value==='sss'?'sss':'normal';state.player.copies=state.difficulty==='sss'?Math.min(state.player.copies,5):Math.max(state.player.copies,8);save();render()})}
function normalizeHistory(d){return{players:(d?.players||[]).map((x,i)=>({id:`p${i}`,name:x[0],nationality:x[1],position:x[2],birthYear:x[3],spans:(x[4]||[]).map(s=>({from:s[0],to:s[1],club:s[2],level:s[3]==='e'?'empréstimo':'profissional'})),talent:{id:`talent-${i}`,name:x[5]?.[0]||'Talento',attribute:x[5]?.[1]==='aceleracao'?'ritmo':x[5]?.[1]||'mental',rarity:x[5]?.[2]||'Épico',passive:x[5]?.[3]||''}})),start:d?.start||START,end:d?.end||END}}
async function loadData(){try{const r=await fetch('data/craques-mini.json',{cache:'no-store'});if(r.ok)history=normalizeHistory(await r.json())}catch{}try{const r=await fetch('data/clubs.generated.json',{cache:'no-store'});if(r.ok){const d=await r.json();clubs=d.clubs||d}}catch{}render()}
function boot(){load();populateStart();bind();injectPanels();if(!localStorage.getItem(SAVE_KEY))$('#onboarding')?.classList.add('show');render();loadData()}
window.CraqueSSS={getState:()=>clone(state),overall,save,newGame};
boot();
})();
